---
- name: Install wget
  hosts: all
  gather_facts: true

  tasks:
    - name: Install wget via Homebrew
      ansible.builtin.shell: /opt/homebrew/bin/brew install wget
      args:
        creates: /opt/homebrew/bin/wget
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install wget via apt (Debian)
      ansible.builtin.apt:
        name: wget
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install wget via pacman (Arch)
      community.general.pacman:
        name: wget
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
