---
- name: Install nmap
  hosts: all
  gather_facts: true

  tasks:
    - name: Install nmap via Homebrew (macOS)
      shell: /opt/homebrew/bin/brew install nmap
      args:
        creates: /opt/homebrew/bin/nmap
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install nmap via apt (Debian)
      apt:
        name: nmap
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian"
