---
- name: Install imagemagick
  hosts: all
  gather_facts: true

  tasks:
    - name: Install imagemagick via Homebrew
      shell: /opt/homebrew/bin/brew install imagemagick
      args:
        creates: /opt/homebrew/bin/magick
      when: ansible_os_family == "Darwin"

    - name: Install imagemagick via apt
      apt:
        name: imagemagick
        state: present
      become: yes
      when: ansible_os_family == "Debian"
