---
- name: Install Waterfox
  hosts: with_browsers
  gather_facts: true

  tasks:
    - name: Install Waterfox via Homebrew Cask (macOS)
      shell: /opt/homebrew/bin/brew install --cask waterfox
      args:
        creates: /Applications/Waterfox.app
      when: ansible_facts['os_family'] == "Darwin"

    - name: Check if Waterfox is installed (Debian)
      stat:
        path: /opt/waterfox
      register: waterfox_check
      when: ansible_facts['os_family'] == "Debian"

    - name: Download Waterfox (Debian)
      get_url:
        url: https://cdn1.waterfox.net/waterfox/releases/latest/linux
        dest: /tmp/waterfox.tar.bz2
      when: ansible_facts['os_family'] == "Debian" and not waterfox_check.stat.exists

    - name: Extract Waterfox (Debian)
      unarchive:
        src: /tmp/waterfox.tar.bz2
        dest: /opt
        remote_src: yes
      become: yes
      when: ansible_facts['os_family'] == "Debian" and not waterfox_check.stat.exists

    - name: Create symlink for Waterfox (Debian)
      file:
        src: /opt/waterfox/waterfox
        dest: /usr/local/bin/waterfox
        state: link
      become: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Clean up Waterfox archive (Debian)
      file:
        path: /tmp/waterfox.tar.bz2
        state: absent
      when: ansible_facts['os_family'] == "Debian"
