---
- name: Install DigitalOcean CLI
  hosts: with_login_tools
  gather_facts: true

  vars:
    doctl_version: "1.104.0"

  tasks:
    - name: Install doctl via Homebrew
      ansible.builtin.shell: /opt/homebrew/bin/brew install doctl
      args:
        creates: /opt/homebrew/bin/doctl
      when: ansible_facts['os_family'] == "Darwin"

    - name: Check if doctl is installed (Debian)
      ansible.builtin.stat:
        path: /usr/local/bin/doctl
      register: doctl_check
      when: ansible_facts['os_family'] == "Debian"

    - name: Download and install doctl (Debian)
      ansible.builtin.shell: |
        curl -sL https://github.com/digitalocean/doctl/releases/download/v{{ doctl_version }}/doctl-{{ doctl_version }}-linux-amd64.tar.gz | tar xz -C /tmp
        install /tmp/doctl /usr/local/bin
        rm -f /tmp/doctl
      become: true
      when: ansible_facts['os_family'] == "Debian" and not doctl_check.stat.exists

    - name: Install doctl via yay (Arch)
      ansible.builtin.shell: yay -S --noconfirm doctl
      args:
        creates: /usr/bin/doctl
      when: ansible_facts['os_family'] == "Archlinux"
