---
- name: Install curl
  hosts: all
  gather_facts: true

  tasks:
    - name: Install curl via Homebrew (macOS)
      ansible.builtin.shell: /opt/homebrew/bin/brew install curl
      args:
        creates: /opt/homebrew/bin/curl
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install curl via apt (Debian)
      ansible.builtin.apt:
        name: curl
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install curl via pacman (Arch)
      community.general.pacman:
        name: curl
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
