---
- name: Install nvm on macOS
  hosts: macs
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Install nvm via Homebrew
      shell: /opt/homebrew/bin/brew install nvm
      args:
        creates: /opt/homebrew/opt/nvm

    - name: Create nvm directory
      file:
        path: "{{ nvm_dir }}"
        state: directory

    - name: Add nvm to shell config
      blockinfile:
        path: ~/.zshrc
        create: true
        marker: "# {mark} NVM"
        block: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "{{ nvm_source }}" ] && \. "{{ nvm_source }}"
          [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

    - name: Install Node.js LTS
      shell: |
        {{ nvm_init }}
        nvm install --lts
        nvm alias default lts/*
      args:
        creates: ~/.nvm/alias/default
