---
- name: Install essential packages
  hosts: debian
  gather_facts: false

  tasks:
    - name: Install essential packages via apt
      apt:
        name:
          - build-essential
          - curl
          - git
          - unzip
        state: present
      become: yes
