---
- name: Prevent sleep during setup (macOS)
  hosts: macs
  gather_facts: false
  tasks:
    - name: Disable sleep
      command: pmset -a disablesleep 1
      become: yes

- name: Update apt cache (Debian)
  hosts: debian
  gather_facts: false
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

- name: Update pacman cache (Arch)
  hosts: arch
  gather_facts: false
  tasks:
    - name: Update pacman cache
      pacman:
        update_cache: yes
      become: yes

- import_playbook: tools/macos/install_macos.yml
- import_playbook: tools/debian/install_debian.yml
- import_playbook: tools/arch/install_arch.yml
- import_playbook: tools/yay/install_yay.yml
- import_playbook: tools/build-essential/install_build-essential.yml
- import_playbook: tools/curl/install_curl.yml
- import_playbook: tools/unzip/install_unzip.yml
- import_playbook: tools/zsh/install_zsh.yml
- import_playbook: tools/ssh/install_ssh.yml
- import_playbook: tools/git/install_git.yml
- import_playbook: tools/keyboard/install_keyboard.yml

- name: Clone dotfiles repo
  hosts: with_login_tools
  gather_facts: false
  tasks:
    - name: Check if dotfiles exists
      stat:
        path: ~/_dotfiles
      register: dotfiles_dir

    - name: Clone dotfiles to ~/_dotfiles
      git:
        repo: git@github.com:matttelliott/_dotfiles.git
        dest: ~/_dotfiles
      when: not dotfiles_dir.stat.exists

    - name: Ensure dotfiles remote uses SSH
      command: git -C ~/_dotfiles remote set-url origin git@github.com:matttelliott/_dotfiles.git
      changed_when: false

- import_playbook: tools/mosh/install_mosh.yml
- import_playbook: tools/homebrew/install_homebrew.yml
- import_playbook: tools/mas/install_mas.yml
- import_playbook: tools/ansible/install_ansible.yml
- import_playbook: tools/starship/install_starship.yml
- import_playbook: tools/node/install_node.yml
- import_playbook: tools/python/install_python.yml
- import_playbook: tools/rust/install_rust.yml
- import_playbook: tools/go/install_go.yml
- import_playbook: tools/lua/install_lua.yml
- import_playbook: tools/tmux/install_tmux.yml
- import_playbook: tools/neovim/install_neovim.yml
- import_playbook: tools/sd/install_sd.yml
- import_playbook: tools/fd/install_fd.yml
- import_playbook: tools/ripgrep/install_ripgrep.yml
- import_playbook: tools/fzf/install_fzf.yml
- import_playbook: tools/jq/install_jq.yml
- import_playbook: tools/htop/install_htop.yml
- import_playbook: tools/nmap/install_nmap.yml
- import_playbook: tools/bat/install_bat.yml
- import_playbook: tools/eza/install_eza.yml
- import_playbook: tools/tree/install_tree.yml
- import_playbook: tools/wget/install_wget.yml
- import_playbook: tools/yt-dlp/install_yt-dlp.yml
- import_playbook: tools/ffmpeg/install_ffmpeg.yml
- import_playbook: tools/imagemagick/install_imagemagick.yml
- import_playbook: tools/pandoc/install_pandoc.yml
- import_playbook: tools/asciiquarium/install_asciiquarium.yml
- import_playbook: tools/lazygit/install_lazygit.yml
- import_playbook: tools/colima/install_colima.yml
- import_playbook: tools/wireguard/install_wireguard.yml
- import_playbook: tools/wireguard_gui/install_wireguard_gui.yml
- import_playbook: tools/fail2ban/install_fail2ban.yml
- import_playbook: tools/1password_cli/install_1password_cli.yml
- import_playbook: tools/doctl/install_doctl.yml
- import_playbook: tools/pulumi/install_pulumi.yml
- import_playbook: tools/awscli/install_awscli.yml
- import_playbook: tools/gh/install_gh.yml
- import_playbook: tools/gcloud/install_gcloud.yml
- import_playbook: tools/kubectl/install_kubectl.yml
- import_playbook: tools/claude-code/install_claude-code.yml
- import_playbook: tools/claude-desktop/install_claude-desktop.yml
- import_playbook: tools/chatgpt-desktop/install_chatgpt-desktop.yml
- import_playbook: tools/codex/install_codex.yml
- import_playbook: tools/1password/install_1password.yml
- import_playbook: tools/wezterm/install_wezterm.yml
- import_playbook: tools/dbeaver/install_dbeaver.yml
- import_playbook: tools/obsidian/install_obsidian.yml
- import_playbook: tools/vlc/install_vlc.yml
- import_playbook: tools/chrome/install_chrome.yml
- import_playbook: tools/chromium/install_chromium.yml
- import_playbook: tools/chrome_canary/install_chrome_canary.yml
- import_playbook: tools/firefox/install_firefox.yml
- import_playbook: tools/firefox_developer/install_firefox_developer.yml
- import_playbook: tools/opera/install_opera.yml
- import_playbook: tools/vivaldi/install_vivaldi.yml
- import_playbook: tools/brave/install_brave.yml
- import_playbook: tools/arc/install_arc.yml
- import_playbook: tools/edge/install_edge.yml
- import_playbook: tools/tor/install_tor.yml
- import_playbook: tools/librewolf/install_librewolf.yml
- import_playbook: tools/waterfox/install_waterfox.yml
- import_playbook: tools/zen/install_zen.yml
- import_playbook: tools/orion/install_orion.yml
- import_playbook: tools/mullvad/install_mullvad.yml
- import_playbook: tools/min/install_min.yml
- import_playbook: tools/steam/install_steam.yml

- name: Allow sleep after setup (macOS)
  hosts: macs
  gather_facts: false
  tasks:
    - name: Re-enable sleep
      command: pmset -a disablesleep 0
      become: yes
