---
- name: Install mosh
  hosts: all
  gather_facts: true

  tasks:
    - name: Install mosh via Homebrew
      ansible.builtin.shell: /opt/homebrew/bin/brew install mosh
      args:
        creates: /opt/homebrew/bin/mosh
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install mosh via apt (Debian)
      ansible.builtin.apt:
        name: mosh
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install mosh via pacman (Arch)
      community.general.pacman:
        name: mosh
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
