---
- name: Install ChatGPT Desktop
  hosts: with_gui_tools:&with_login_tools:&with_ai_tools
  gather_facts: true

  tasks:
    - name: Install ChatGPT Desktop via Homebrew (macOS)
      shell: /opt/homebrew/bin/brew install --cask chatgpt
      args:
        creates: /Applications/ChatGPT.app
      when: ansible_facts['os_family'] == "Darwin"
