---
- name: Install and configure fail2ban
  hosts: all
  gather_facts: true

  tasks:
    - name: Install fail2ban via apt (Debian)
      ansible.builtin.apt:
        name: fail2ban
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install fail2ban via pacman (Arch)
      community.general.pacman:
        name: fail2ban
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Create jail.local config
      ansible.builtin.copy:
        src: jail.local
        dest: /etc/fail2ban/jail.local
        mode: '0644'
      become: true
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"]

    - name: Enable and start fail2ban
      ansible.builtin.systemd:
        name: fail2ban
        enabled: true
        state: started
      become: true
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"]
