---
- name: Install and configure fail2ban
  hosts: all
  gather_facts: true

  tasks:
    - name: Install fail2ban via apt (Debian)
      apt:
        name: fail2ban
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install fail2ban via pacman (Arch)
      pacman:
        name: fail2ban
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Create jail.local config
      copy:
        src: jail.local
        dest: /etc/fail2ban/jail.local
        mode: '0644'
      become: yes
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"]

    - name: Enable and start fail2ban
      systemd:
        name: fail2ban
        enabled: yes
        state: started
      become: yes
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"]
