---
- name: Install eza
  hosts: all
  gather_facts: true

  tasks:
    - name: Install eza via Homebrew
      shell: /opt/homebrew/bin/brew install eza
      args:
        creates: /opt/homebrew/bin/eza
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install eza via cargo (Debian)
      shell: ~/.cargo/bin/cargo install eza
      args:
        creates: ~/.cargo/bin/eza
      when: ansible_facts['os_family'] == "Debian"

    - name: Install eza via pacman (Arch)
      pacman:
        name: eza
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Create zsh config directory
      file:
        path: ~/.config/zsh
        state: directory

    - name: Install eza aliases
      copy:
        src: eza.zsh
        dest: ~/.config/zsh/eza.zsh

    - name: Source eza aliases in zshrc
      lineinfile:
        path: ~/.zshrc
        line: 'source ~/.config/zsh/eza.zsh'
        create: yes
