- name: Install Firefox
  hosts: with_browsers
  gather_facts: true
  tasks:
    - name: Install Firefox via Homebrew Cask (macOS)
      ansible.builtin.shell: /opt/homebrew/bin/brew install --cask firefox
      args:
        creates: /Applications/Firefox.app
      when: ansible_facts['os_family'] == "Darwin"
    - name: Install Firefox ESR via apt (Debian)
      ansible.builtin.apt:
        name: firefox-esr
        state: present
      become: true
      register: firefox_esr_result
      ignore_errors: true
      when: ansible_facts['os_family'] == "Debian"
    - name: Install Firefox via apt (Debian fallback)
      ansible.builtin.apt:
        name: firefox
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian" and firefox_esr_result is failed
    - name: Install Firefox via pacman (Arch)
      community.general.pacman:
        name: firefox
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
