---
- name: Install Pulumi
  hosts: all
  gather_facts: true

  tasks:
    - name: Install Pulumi via Homebrew
      ansible.builtin.shell: /opt/homebrew/bin/brew install pulumi
      args:
        creates: /opt/homebrew/bin/pulumi
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install Pulumi via official installer (Linux)
      # Pulumi installer with pinned version (update periodically)
      # Latest version: https://github.com/pulumi/pulumi/releases
      ansible.builtin.shell: curl -fsSL https://get.pulumi.com | sh -s -- --version 3.216.0
      args:
        creates: ~/.pulumi/bin/pulumi
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"]

    - name: Add Pulumi to shell config
      ansible.builtin.blockinfile:
        path: ~/.zshrc
        create: true
        marker: "# {mark} PULUMI"
        block: |
          export PATH=$PATH:~/.pulumi/bin
