---
- name: Install 1Password CLI on macOS
  hosts: with_login_tools
  gather_facts: false

  tasks:
    - name: Install 1Password CLI via Homebrew
      shell: /opt/homebrew/bin/brew install 1password-cli
      args:
        creates: /opt/homebrew/bin/op
