---
- name: Configure Arch system preferences
  hosts: arch
  gather_facts: false

  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ ansible_host }}"
      become: true

    - name: Update package database
      community.general.pacman:
        update_cache: true
      become: true
