---
- name: Configure Arch system preferences
  hosts: arch
  gather_facts: false

  tasks:
    - name: Set hostname
      hostname:
        name: "{{ ansible_host }}"
      become: yes

    - name: Update package database
      pacman:
        update_cache: yes
      become: yes
