---
- name: Install asciiquarium
  hosts: all
  gather_facts: true

  tasks:
    - name: Install asciiquarium via Homebrew
      ansible.builtin.shell: /opt/homebrew/bin/brew install asciiquarium
      args:
        creates: /opt/homebrew/bin/asciiquarium
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install asciiquarium dependencies via apt (Debian)
      ansible.builtin.apt:
        name:
          - libcurses-perl
          - cpanminus
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Term::Animation via cpan (Debian)
      ansible.builtin.shell: cpanm Term::Animation
      args:
        creates: /usr/local/share/perl/*/Term/Animation.pm
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Download and install asciiquarium (Debian)
      ansible.builtin.shell: |
        curl -sL https://robobunny.com/projects/asciiquarium/asciiquarium.tar.gz | tar xz -C /tmp
        install /tmp/asciiquarium_1.1/asciiquarium /usr/local/bin/
        rm -rf /tmp/asciiquarium_1.1
      args:
        creates: /usr/local/bin/asciiquarium
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install asciiquarium via yay (Arch)
      ansible.builtin.shell: yay -S --noconfirm asciiquarium
      args:
        creates: /usr/bin/asciiquarium
      when: ansible_facts['os_family'] == "Archlinux"
