---
- name: Install and configure SSH
  hosts: all
  gather_facts: true

  tasks:
    - name: Install openssh-server (Debian)
      apt:
        name: openssh-server
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install openssh (Arch)
      pacman:
        name: openssh
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Enable and start sshd (Debian)
      systemd:
        name: ssh
        enabled: yes
        state: started
      become: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Enable and start sshd (Arch)
      systemd:
        name: sshd
        enabled: yes
        state: started
      become: yes
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Ensure .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Add macbook public key to authorized_keys
      authorized_key:
        user: "{{ ansible_facts['user_id'] }}"
        key: "{{ ssh_public_key }}"
        state: present

    - name: Install SSH config
      template:
        src: config.j2
        dest: ~/.ssh/config
        mode: '0600'

    - name: Add host keys to known_hosts
      shell: ssh-keyscan -H {{ item }}.home.lan >> ~/.ssh/known_hosts 2>/dev/null
      args:
        creates: ~/.ssh/.known_hosts_{{ item }}
      loop:
        - macbookair
        - macmini
        - desktop
        - miniserver
      ignore_errors: yes

    - name: Mark known_hosts as populated
      file:
        path: ~/.ssh/.known_hosts_{{ item }}
        state: touch
        mode: '0600'
      loop:
        - macbookair
        - macmini
        - desktop
        - miniserver

    - name: Check if 1Password service account token exists
      stat:
        path: ~/.config/op/service-account-token
      register: op_token_file

    - name: Find op CLI path
      shell: command -v op || echo /opt/homebrew/bin/op
      register: op_cli_path
      changed_when: false

    - name: Check if op CLI is available
      stat:
        path: "{{ op_cli_path.stdout }}"
      register: op_cli_check

    - name: Fetch SSH private key from 1Password
      shell: |
        export OP_SERVICE_ACCOUNT_TOKEN=$(cat ~/.config/op/service-account-token)
        {{ op_cli_path.stdout }} read "{{ op_ssh_private_key_ref }}"
      register: op_ssh_key
      when:
        - op_token_file.stat.exists
        - op_cli_check.stat.exists
        - op_ssh_private_key_ref is defined
        - op_ssh_private_key_ref | length > 0
      no_log: true

    - name: Deploy SSH private key
      copy:
        content: "{{ op_ssh_key.stdout }}\n"
        dest: ~/.ssh/id_rsa
        mode: '0600'
      when: op_ssh_key is defined and op_ssh_key.stdout is defined and op_ssh_key.stdout | length > 0
      no_log: true

    - name: Generate SSH public key from private key
      shell: ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
      args:
        creates: ~/.ssh/id_rsa.pub
      when: op_ssh_key is defined and op_ssh_key.stdout is defined and op_ssh_key.stdout | length > 0
