---
- name: Install and configure SSH
  hosts: all
  gather_facts: true

  tasks:
    - name: Install openssh-server (Debian)
      ansible.builtin.apt:
        name: openssh-server
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install openssh (Arch)
      community.general.pacman:
        name: openssh
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Enable and start sshd (Debian)
      ansible.builtin.systemd:
        name: ssh
        enabled: true
        state: started
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Enable and start sshd (Arch)
      ansible.builtin.systemd:
        name: sshd
        enabled: true
        state: started
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Add macbook public key to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ ansible_facts['user_id'] }}"
        key: "{{ ssh_public_key }}"
        state: present
      when: ssh_public_key | default('') | length > 0

    - name: Install SSH config
      ansible.builtin.template:
        src: config.j2
        dest: ~/.ssh/config
        mode: '0600'

    - name: Check if hosts already in known_hosts
      ansible.builtin.command: ssh-keygen -F {{ item }}.home.lan
      register: known_hosts_check
      changed_when: false
      failed_when: false
      loop:
        - macbookair
        - macmini
        - desktop
        - optiplex-0

    - name: Add missing host keys to known_hosts
      ansible.builtin.shell: ssh-keyscan -H {{ item.item }}.home.lan >> ~/.ssh/known_hosts 2>/dev/null
      loop: "{{ known_hosts_check.results }}"
      loop_control:
        label: "{{ item.item }}"
      when: item.rc != 0
      changed_when: true
      failed_when: false

    - name: Check if 1Password service account token exists
      ansible.builtin.stat:
        path: ~/.config/op/service-account-token
      register: op_token_file

    - name: Find op CLI path
      ansible.builtin.shell: command -v op || echo /opt/homebrew/bin/op
      register: op_cli_path
      changed_when: false

    - name: Check if op CLI is available
      ansible.builtin.stat:
        path: "{{ op_cli_path.stdout }}"
      register: op_cli_check

    - name: Fetch SSH private key from 1Password
      ansible.builtin.shell: |
        export OP_SERVICE_ACCOUNT_TOKEN=$(cat ~/.config/op/service-account-token)
        {{ op_cli_path.stdout }} read "{{ op_ssh_private_key_ref }}"
      register: op_ssh_key
      when:
        - op_token_file.stat.exists
        - op_cli_check.stat.exists
        - op_ssh_private_key_ref is defined
        - op_ssh_private_key_ref | length > 0
      no_log: true

    - name: Deploy SSH private key
      ansible.builtin.copy:
        content: "{{ op_ssh_key.stdout }}\n"
        dest: ~/.ssh/id_rsa
        mode: '0600'
      when: op_ssh_key is defined and op_ssh_key.stdout is defined and op_ssh_key.stdout | length > 0
      no_log: true

    - name: Generate SSH public key from private key
      ansible.builtin.shell: ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
      args:
        creates: ~/.ssh/id_rsa.pub
      when: op_ssh_key is defined and op_ssh_key.stdout is defined and op_ssh_key.stdout | length > 0
