---
- name: Install and configure SSH
  hosts: all
  gather_facts: true

  tasks:
    - name: Install openssh-server (Debian)
      ansible.builtin.apt:
        name: openssh-server
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install openssh (Arch)
      community.general.pacman:
        name: openssh
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Enable and start sshd (Debian)
      ansible.builtin.systemd:
        name: ssh
        enabled: true
        state: started
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Enable and start sshd (Arch)
      ansible.builtin.systemd:
        name: sshd
        enabled: true
        state: started
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: "0700"
