---
- name: Install Raycast
  hosts: macs:&with_gui_tools
  gather_facts: false

  tasks:
    - name: Install Raycast via Homebrew
      shell: /opt/homebrew/bin/brew install --cask raycast
      args:
        creates: /Applications/Raycast.app

    - name: Disable Spotlight keyboard shortcut (Cmd+Space)
      shell: |
        /usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:64:enabled false" ~/Library/Preferences/com.apple.symbolichotkeys.plist 2>/dev/null || \
        /usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:64:enabled bool false" ~/Library/Preferences/com.apple.symbolichotkeys.plist
      changed_when: false

    - name: Restart cfprefsd to apply shortcut changes
      command: killall cfprefsd
      changed_when: false
      failed_when: false
