---
- name: Install nvm on macOS
  hosts: macs
  gather_facts: false

  tasks:
    - name: Install nvm via Homebrew
      shell: /opt/homebrew/bin/brew install nvm
      args:
        creates: /opt/homebrew/opt/nvm

    - name: Create nvm directory
      file:
        path: ~/.nvm
        state: directory

    - name: Add nvm to shell config
      blockinfile:
        path: ~/.zshrc
        create: true
        marker: "# {mark} NVM"
        block: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
          [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

    - name: Install Node.js LTS
      shell: |
        export NVM_DIR="$HOME/.nvm"
        . /opt/homebrew/opt/nvm/nvm.sh
        nvm install --lts
        nvm alias default lts/*
      args:
        creates: ~/.nvm/alias/default
