---
- name: Install WezTerm
  hosts: with_gui_tools
  gather_facts: true

  tasks:
    - name: Install WezTerm via Homebrew Cask
      ansible.builtin.shell: /opt/homebrew/bin/brew install --cask wezterm
      args:
        creates: /Applications/WezTerm.app
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install DejaVu Nerd Font via Homebrew Cask
      ansible.builtin.shell: /opt/homebrew/bin/brew install --cask font-dejavu-sans-mono-nerd-font
      when: ansible_facts['os_family'] == "Darwin"

    - name: Check if WezTerm is installed
      ansible.builtin.stat:
        path: /usr/bin/wezterm
      register: wezterm_check
      when: ansible_facts['os_family'] == "Debian"

    - name: Add WezTerm apt repository
      ansible.builtin.shell: |
        curl -fsSL https://apt.fury.io/wez/gpg.key | gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
        echo "deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *" | tee /etc/apt/sources.list.d/wezterm.list > /dev/null
      become: true
      when: ansible_facts['os_family'] == "Debian" and not wezterm_check.stat.exists

    - name: Install WezTerm via apt
      ansible.builtin.apt:
        name: wezterm
        state: present
        update_cache: true
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Create fonts directory
      ansible.builtin.file:
        path: ~/.local/share/fonts
        state: directory
      when: ansible_facts['os_family'] == "Debian"

    - name: Check if DejaVu Nerd Font is installed
      ansible.builtin.stat:
        path: ~/.local/share/fonts/DejaVuSansMNerdFont-Regular.ttf
      register: dejavu_font_check
      when: ansible_facts['os_family'] == "Debian"

    - name: Install DejaVu Nerd Font (Debian)
      ansible.builtin.shell: |
        curl -fLo /tmp/DejaVuSansMono.tar.xz https://github.com/ryanoasis/nerd-fonts/releases/latest/download/DejaVuSansMono.tar.xz
        tar -xf /tmp/DejaVuSansMono.tar.xz -C ~/.local/share/fonts
        fc-cache -fv
        rm /tmp/DejaVuSansMono.tar.xz
      when: ansible_facts['os_family'] == "Debian" and not dejavu_font_check.stat.exists

    - name: Install WezTerm via pacman (Arch)
      community.general.pacman:
        name: wezterm
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Install DejaVu Nerd Font via pacman (Arch)
      community.general.pacman:
        name: ttf-dejavu-nerd
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Install WezTerm config
      ansible.builtin.copy:
        src: wezterm.lua
        dest: ~/.wezterm.lua

    - name: Create ~/.local/bin directory
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory
      when: ansible_facts['os_family'] != "Darwin"

    - name: Install clip2path script for image pasting (Linux)
      ansible.builtin.copy:
        src: clip2path
        dest: ~/.local/bin/clip2path
        mode: "0755"
      when: ansible_facts['os_family'] != "Darwin"
