---
- name: Install gsd-worktree shell functions
  hosts: all
  gather_facts: true

  tasks:
    - name: Create zsh config directory
      file:
        path: ~/.config/zsh
        state: directory

    - name: Install gsd-worktree functions
      copy:
        src: gsd-worktree.zsh
        dest: ~/.config/zsh/gsd-worktree.zsh

    - name: Source gsd-worktree in zshrc
      lineinfile:
        path: ~/.zshrc
        line: 'source ~/.config/zsh/gsd-worktree.zsh'
        create: true
