- name: Install dust
  hosts: all
  gather_facts: true
  tasks:
    - name: Install dust via Homebrew
      ansible.builtin.shell: /opt/homebrew/bin/brew install dust
      args:
        creates: /opt/homebrew/bin/dust
      when: ansible_facts['os_family'] == "Darwin"
    - name: Install dust via cargo (Debian)
      ansible.builtin.shell: ~/.cargo/bin/cargo install du-dust
      args:
        creates: ~/.cargo/bin/dust
      when: ansible_facts['os_family'] == "Debian"
    - name: Install dust via pacman (Arch)
      community.general.pacman:
        name: dust
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
