---
- name: Install Google Cloud CLI on macOS
  hosts: with_login_tools
  gather_facts: false

  tasks:
    - name: Install Google Cloud SDK via Homebrew Cask
      shell: /opt/homebrew/bin/brew install --cask google-cloud-sdk
      args:
        creates: /opt/homebrew/Caskroom/google-cloud-sdk
