---
# GPU Driver Installation
#
# Detects GPU hardware and installs appropriate drivers with gaming support.
# Includes Vulkan, 32-bit libraries, and proper driver configuration.
#
# Supported GPUs:
#   - NVIDIA: Proprietary drivers with nouveau blacklist
#   - AMD: Mesa with Vulkan (RADV)
#   - Intel: Mesa with Vulkan (ANV)

- name: Install GPU Drivers
  hosts: all
  gather_facts: true

  tasks:
    # GPU Detection (Linux only)
    - name: Detect GPU hardware
      shell: lspci | grep -iE 'vga|3d|display'
      register: gpu_lspci
      changed_when: false
      failed_when: false
      check_mode: no
      when: ansible_facts['os_family'] != "Darwin"

    - name: Set GPU type facts
      set_fact:
        has_nvidia: "{{ 'NVIDIA' in gpu_lspci.stdout | default('') }}"
        has_amd: "{{ 'AMD' in gpu_lspci.stdout | default('') or 'ATI' in gpu_lspci.stdout | default('') }}"
        has_intel: "{{ 'Intel' in gpu_lspci.stdout | default('') }}"
      when: ansible_facts['os_family'] != "Darwin"

    - name: Display detected GPUs
      debug:
        msg: "Detected GPUs - NVIDIA: {{ has_nvidia }}, AMD: {{ has_amd }}, Intel: {{ has_intel }}"
      when: ansible_facts['os_family'] != "Darwin"

    # Arch Linux - Common Vulkan loader
    - name: Install Vulkan ICD loader (Arch)
      pacman:
        name:
          - vulkan-icd-loader
          - lib32-vulkan-icd-loader
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Archlinux"

    # Arch Linux - NVIDIA (using nvidia-dkms for kernel-agnostic support)
    - name: Install NVIDIA drivers (Arch)
      pacman:
        name:
          - nvidia-dkms
          - nvidia-utils
          - lib32-nvidia-utils
          - nvidia-settings
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Archlinux" and has_nvidia | default(false)

    - name: Blacklist nouveau driver (Arch)
      copy:
        dest: /etc/modprobe.d/blacklist-nouveau.conf
        content: |
          blacklist nouveau
          options nouveau modeset=0
        mode: '0644'
      become: yes
      when: ansible_facts['os_family'] == "Archlinux" and has_nvidia | default(false)

    # Arch Linux - AMD
    - name: Install AMD drivers (Arch)
      pacman:
        name:
          - mesa
          - lib32-mesa
          - vulkan-radeon
          - lib32-vulkan-radeon
          - xf86-video-amdgpu
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Archlinux" and has_amd | default(false)

    # Arch Linux - Intel
    - name: Install Intel drivers (Arch)
      pacman:
        name:
          - mesa
          - lib32-mesa
          - vulkan-intel
          - lib32-vulkan-intel
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Archlinux" and has_intel | default(false)

    # Arch Linux - Add user to video group
    - name: Add user to video group (Arch)
      user:
        name: "{{ ansible_facts['user_id'] }}"
        groups: video
        append: yes
      become: yes
      when: ansible_facts['os_family'] == "Archlinux"

    # Debian - Enable non-free repos for NVIDIA
    - name: Check if non-free repos enabled (Debian)
      shell: grep -E 'non-free|contrib' /etc/apt/sources.list /etc/apt/sources.list.d/*.list 2>/dev/null || true
      register: nonfree_check
      changed_when: false
      when: ansible_facts['os_family'] == "Debian" and has_nvidia | default(false)

    - name: Enable non-free and contrib repos (Debian)
      shell: |
        sed -i 's/main$/main contrib non-free non-free-firmware/' /etc/apt/sources.list
      become: yes
      when: ansible_facts['os_family'] == "Debian" and has_nvidia | default(false) and 'non-free' not in nonfree_check.stdout
      changed_when: true

    - name: Update apt cache after enabling non-free (Debian)
      apt:
        update_cache: yes
      become: yes
      when: ansible_facts['os_family'] == "Debian" and has_nvidia | default(false) and 'non-free' not in nonfree_check.stdout

    # Debian - NVIDIA
    - name: Install NVIDIA drivers (Debian)
      apt:
        name:
          - nvidia-driver
          - nvidia-settings
          - firmware-misc-nonfree
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian" and has_nvidia | default(false)

    # Debian - AMD
    - name: Install AMD drivers (Debian)
      apt:
        name:
          - firmware-amd-graphics
          - mesa-vulkan-drivers
          - libvulkan1
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian" and has_amd | default(false)

    # Debian - Intel
    - name: Install Intel drivers (Debian)
      apt:
        name:
          - intel-media-va-driver
          - mesa-vulkan-drivers
          - libvulkan1
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian" and has_intel | default(false)

    # Debian - Add user to video group
    - name: Add user to video group (Debian)
      user:
        name: "{{ ansible_facts['user_id'] }}"
        groups: video
        append: yes
      become: yes
      when: ansible_facts['os_family'] == "Debian"

    # macOS - Log GPU info (drivers are built-in via Metal)
    - name: Get GPU info (macOS)
      shell: system_profiler SPDisplaysDataType
      register: macos_gpu_info
      changed_when: false
      when: ansible_facts['os_family'] == "Darwin"

    - name: Display macOS GPU info
      debug:
        msg: "{{ macos_gpu_info.stdout_lines }}"
      when: ansible_facts['os_family'] == "Darwin"
