---
- name: Install tree
  hosts: all
  gather_facts: true

  tasks:
    - name: Install tree via Homebrew
      shell: /opt/homebrew/bin/brew install tree
      args:
        creates: /opt/homebrew/bin/tree
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install tree via apt (Debian)
      apt:
        name: tree
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install tree via pacman (Arch)
      pacman:
        name: tree
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Archlinux"
