---
- name: Install Homebrew on macOS
  hosts: macs
  gather_facts: false

  tasks:
    - name: Install Xcode Command Line Tools
      ansible.builtin.raw: |
        if [ ! -f /Library/Developer/CommandLineTools/usr/bin/git ]; then
          touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
          softwareupdate -l | grep -o 'Command Line Tools.*' | head -1 | xargs -I {} softwareupdate -i "{}"
          rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
        fi

    - name: Check if Homebrew is installed
      ansible.builtin.stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

    - name: Install Homebrew
      # Homebrew installer pinned to commit 90fa3d5881cedc0d60c4a3cc5babdb867ef42e5a (2026-01-23)
      # Verify/update at: https://github.com/Homebrew/install/commits/master
      ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/90fa3d5881cedc0d60c4a3cc5babdb867ef42e5a/install.sh)"
      environment:
        NONINTERACTIVE: "1"
      become: true
      when: not homebrew_check.stat.exists
