---
- name: Install Team Fortress 2
  hosts: with_games
  gather_facts: true

  vars:
    tf2_app_id: "440"
    tf2_launch_options: "-novid -nojoy -nosteamcontroller -nohltv -particles 1 -vulkan -windowed -noborder"
    tf2_cfg_src: "{{ playbook_dir }}/cfg"
    tf2_cfg_dest_linux: "~/.steam/steam/steamapps/common/Team Fortress 2/tf/cfg"
    tf2_cfg_dest_mac: "~/Library/Application Support/Steam/steamapps/common/Team Fortress 2/tf/cfg"
    tf2_custom_linux: "~/.steam/steam/steamapps/common/Team Fortress 2/tf/custom"
    tf2_custom_mac: "~/Library/Application Support/Steam/steamapps/common/Team Fortress 2/tf/custom"
    tf2_hud_storage: "{{ ansible_env.HOME }}/.local/share/tf2-huds"
    steam_login_file_linux: "~/.steam/steam/config/loginusers.vdf"
    steam_login_file_mac: "~/Library/Application Support/Steam/config/loginusers.vdf"

    # Default HUDs to install (first one will be active, rest disabled)
    tf2_huds:
      - name: rayshud
        repo: raysfire/rayshud
      - name: flawhud
        repo: CriticalFlaw/flawhud
      - name: budhud
        repo: rbjaxter/budhud
      - name: zeeshud
        repo: Zeesastrous/ZeesHUD
      - name: m0rehud
        repo: Hypnootize/m0rehud
      - name: hypnotizehud
        repo: Hypnootize/hypnotizehud
      - name: hexhud
        repo: Hypnootize/hexhud
      - name: 7hud
        repo: Sevin7/7hud
      - name: kbnhud
        repo: Jotunn/kbnhud
      - name: peachhud
        repo: PapaPeach/peachhud

  tasks:
    - name: Set OS-specific paths
      ansible.builtin.set_fact:
        tf2_cfg_dest: "{{ tf2_cfg_dest_mac if ansible_facts['os_family'] == 'Darwin' else tf2_cfg_dest_linux }}"
        tf2_custom_dest: "{{ tf2_custom_mac if ansible_facts['os_family'] == 'Darwin' else tf2_custom_linux }}"
        steam_login_file: "{{ steam_login_file_mac if ansible_facts['os_family'] == 'Darwin' else steam_login_file_linux }}"

    - name: Check Steam login file exists
      ansible.builtin.stat:
        path: "{{ steam_login_file }}"
      register: steam_login_stat

    - name: Read Steam login file
      ansible.builtin.slurp:
        src: "{{ steam_login_file }}"
      register: steam_login_content
      when: steam_login_stat.stat.exists

    - name: Check if Steam user is logged in
      ansible.builtin.set_fact:
        steam_logged_in: "{{ steam_login_stat.stat.exists and ('MostRecent' in (steam_login_content.content | b64decode)) }}"

    - name: Fail if Steam not logged in
      ansible.builtin.fail:
        msg: "Steam must be installed and logged in to install TF2. Open Steam and log in first."
      when: not steam_logged_in

    - name: Check if TF2 is installed
      ansible.builtin.stat:
        path: "{{ tf2_cfg_dest | dirname | dirname }}"
      register: tf2_dir

    - name: Install TF2 via Steam (macOS)
      ansible.builtin.command: open "steam://install/{{ tf2_app_id }}"
      when:
        - ansible_facts['os_family'] == "Darwin"
        - not tf2_dir.stat.exists
      changed_when: true

    - name: Install TF2 via Steam (Linux)
      ansible.builtin.command: steam "steam://install/{{ tf2_app_id }}"
      when:
        - ansible_facts['os_family'] != "Darwin"
        - not tf2_dir.stat.exists
      changed_when: true

    - name: Wait for TF2 installation
      ansible.builtin.pause:
        prompt: |
          Steam should now be prompting to install TF2.
          Press ENTER after TF2 installation completes (or Ctrl+C to skip config deployment)
      when: not tf2_dir.stat.exists

    - name: Re-check if TF2 is installed
      ansible.builtin.stat:
        path: "{{ tf2_cfg_dest | dirname | dirname }}"
      register: tf2_dir

    - name: Create TF2 cfg directory
      ansible.builtin.file:
        path: "{{ tf2_cfg_dest }}"
        state: directory
        mode: "0755"
      when: tf2_dir.stat.exists

    - name: Create crosshairswitcher directory
      ansible.builtin.file:
        path: "{{ tf2_cfg_dest }}/crosshairswitcher"
        state: directory
        mode: "0755"
      when: tf2_dir.stat.exists

    - name: Create tweaks directory
      ansible.builtin.file:
        path: "{{ tf2_cfg_dest }}/tweaks"
        state: directory
        mode: "0755"
      when: tf2_dir.stat.exists

    - name: Copy TF2 config files
      ansible.builtin.copy:
        src: "{{ tf2_cfg_src }}/"
        dest: "{{ tf2_cfg_dest }}/"
        mode: "0644"
      when: tf2_dir.stat.exists

    # =========================================================================
    # Custom Overrides (server browser size, etc.)
    # =========================================================================
    - name: Create TF2 custom directory
      ansible.builtin.file:
        path: "{{ tf2_custom_dest }}"
        state: directory
        mode: "0755"
      when: tf2_dir.stat.exists

    - name: Copy custom overrides
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/custom-overrides/"
        dest: "{{ tf2_custom_dest }}/custom-overrides/"
        mode: "0644"
      when: tf2_dir.stat.exists

    # =========================================================================
    # HUD Installation
    # =========================================================================
    - name: Check which HUDs are already installed
      ansible.builtin.stat:
        path: "{{ tf2_custom_dest }}/{{ item.name }}"
      loop: "{{ tf2_huds }}"
      register: hud_check
      when: tf2_dir.stat.exists

    - name: Check which HUDs are in storage
      ansible.builtin.stat:
        path: "{{ tf2_hud_storage }}/{{ item.name }}"
      loop: "{{ tf2_huds }}"
      register: hud_check_storage
      when: tf2_dir.stat.exists

    - name: Download HUDs from GitHub
      ansible.builtin.get_url:
        url: "https://github.com/{{ item.item.repo }}/archive/refs/heads/master.zip"
        dest: "/tmp/{{ item.item.name }}.zip"
        mode: "0644"
      loop: "{{ hud_check.results }}"
      loop_control:
        index_var: hud_idx
      when:
        - tf2_dir.stat.exists
        - not item.stat.exists
        - not (hud_check_storage.results[hud_idx].stat.exists | default(false))
      register: hud_downloads
      ignore_errors: true

    - name: Extract HUDs to custom folder
      ansible.builtin.unarchive:
        src: "/tmp/{{ item.item.item.name }}.zip"
        dest: "{{ tf2_custom_dest }}"
        remote_src: true
      loop: "{{ hud_downloads.results }}"
      when:
        - tf2_dir.stat.exists
        - item.changed | default(false)
      ignore_errors: true

    - name: Create HUD storage directory
      ansible.builtin.file:
        path: "{{ tf2_hud_storage }}"
        state: directory
        mode: "0755"

    - name: Find extracted HUD folders
      ansible.builtin.find:
        paths: "{{ tf2_custom_dest }}"
        patterns: "*-master"
        file_type: directory
      register: extracted_huds
      when: tf2_dir.stat.exists

    - name: Move extracted HUDs to storage
      ansible.builtin.shell: |
        mv "{{ item.path }}" "{{ tf2_hud_storage }}/{{ item.path | basename | regex_replace('-master$', '') }}"
      args:
        removes: "{{ item.path }}"
        creates: "{{ tf2_hud_storage }}/{{ item.path | basename | regex_replace('-master$', '') }}"
      loop: "{{ extracted_huds.files | default([]) }}"
      when: tf2_dir.stat.exists

    - name: Check if 7hud is in storage
      ansible.builtin.stat:
        path: "{{ tf2_hud_storage }}/7hud"
      register: default_hud_storage

    - name: Check if 7hud is already active
      ansible.builtin.stat:
        path: "{{ tf2_custom_dest }}/7hud"
      register: default_hud_active

    - name: Enable 7hud (default HUD)
      ansible.builtin.shell: |
        mv "{{ tf2_hud_storage }}/7hud" "$HOME/.steam/steam/steamapps/common/Team Fortress 2/tf/custom/7hud"
      when:
        - tf2_dir.stat.exists
        - default_hud_storage.stat.exists | default(false)
        - not (default_hud_active.stat.exists | default(false))

    - name: Clean up HUD zip files
      ansible.builtin.file:
        path: "/tmp/{{ item.name }}.zip"
        state: absent
      loop: "{{ tf2_huds }}"

    # =========================================================================
    # Set Steam Launch Options
    # =========================================================================
    - name: Find Steam userdata directory
      ansible.builtin.find:
        paths: "~/.steam/steam/userdata"
        file_type: directory
        recurse: false
      register: steam_userdata

    - name: Set TF2 launch options in Steam
      ansible.builtin.shell: |
        CONFIG_FILE="{{ steam_userdata.files[0].path }}/config/localconfig.vdf"
        LAUNCH_OPTS='{{ tf2_launch_options }}'

        if [[ ! -f "$CONFIG_FILE" ]]; then
          echo "Config file not found"
          exit 0
        fi

        # Check if TF2 app section exists and has LaunchOptions
        if grep -q '"440"' "$CONFIG_FILE"; then
          # Use Python to safely modify VDF file
          python3 << 'PYTHON'
        import re
        import sys

        config_file = "{{ steam_userdata.files[0].path }}/config/localconfig.vdf"
        launch_opts = '{{ tf2_launch_options }}'

        with open(config_file, 'r') as f:
            content = f.read()

        # Pattern to find the 440 block and its LaunchOptions
        # This handles the nested VDF structure
        in_440_block = False
        brace_depth = 0
        lines = content.split('\n')
        new_lines = []
        found_launch_options = False
        inserted = False

        for i, line in enumerate(lines):
            stripped = line.strip()

            if '"440"' in stripped and not in_440_block:
                in_440_block = True
                brace_depth = 0
                new_lines.append(line)
                continue

            if in_440_block:
                if '{' in stripped:
                    brace_depth += stripped.count('{')
                if '}' in stripped:
                    brace_depth -= stripped.count('}')

                if '"LaunchOptions"' in stripped:
                    # Replace existing LaunchOptions
                    indent = len(line) - len(line.lstrip())
                    new_lines.append(' ' * indent + f'"LaunchOptions"\t\t"{launch_opts}"')
                    found_launch_options = True
                    inserted = True
                    continue

                if brace_depth == 0 and '}' in stripped:
                    # End of 440 block, insert LaunchOptions if not found
                    if not found_launch_options and not inserted:
                        indent = len(line) - len(line.lstrip()) + 1
                        new_lines.append('\t\t\t\t\t\t\t"LaunchOptions"\t\t"' + launch_opts + '"')
                        inserted = True
                    in_440_block = False

            new_lines.append(line)

        with open(config_file, 'w') as f:
            f.write('\n'.join(new_lines))

        print(f"Set launch options for TF2: {launch_opts}")
        PYTHON
        fi
      args:
        executable: /bin/bash
      when:
        - tf2_dir.stat.exists
        - steam_userdata.files | length > 0
      register: launch_options_result
      changed_when: "'Set launch options' in launch_options_result.stdout"

    - name: Display deployment info
      ansible.builtin.debug:
        msg: |
          TF2 configs deployed to: {{ tf2_cfg_dest }}
          HUDs installed to: {{ tf2_custom_dest }}

          Active HUD: 7hud (use 'tf2-hud' to switch)
          Launch options: {{ tf2_launch_options }}
      when: tf2_dir.stat.exists

    - name: Warn if TF2 not installed
      ansible.builtin.debug:
        msg: |
          TF2 installation not detected.
          Re-run this playbook after TF2 finishes installing.
      when: not tf2_dir.stat.exists

    - name: Source TF2 shell functions in zshrc
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: '[[ -f "$DOTFILES/tools/tf2/tf2.zsh" ]] && source "$DOTFILES/tools/tf2/tf2.zsh"'
        regexp: 'tf2\.zsh'
        state: present
