---
- name: Install 1Password on macOS
  hosts: with_login_tools:&with_gui_tools
  gather_facts: false

  tasks:
    - name: Install 1Password via Homebrew Cask
      shell: /opt/homebrew/bin/brew install --cask 1password
      args:
        creates: /Applications/1Password.app
