- name: Install Go
  hosts: all
  gather_facts: true
  vars:
    go_version: "1.23.4"
  tasks:
    - name: Check if Go is installed
      ansible.builtin.stat:
        path: /usr/local/go/bin/go
      register: go_binary
    # macOS: Use .pkg installer
    - name: Download Go installer (macOS)
      ansible.builtin.get_url:
        url: "https://go.dev/dl/go{{ go_version }}.darwin-arm64.pkg"
        dest: /tmp/go.pkg
      when: ansible_facts['os_family'] == "Darwin" and not go_binary.stat.exists
    - name: Install Go (macOS)
      ansible.builtin.command: installer -pkg /tmp/go.pkg -target /
      become: true
      when: ansible_facts['os_family'] == "Darwin" and not go_binary.stat.exists
    - name: Clean up installer (macOS)
      ansible.builtin.file:
        path: /tmp/go.pkg
        state: absent
      when: ansible_facts['os_family'] == "Darwin" and not go_binary.stat.exists
    # Linux: Use tarball
    - name: Download Go tarball (Linux)
      ansible.builtin.get_url:
        url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: /tmp/go.tar.gz
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"] and not go_binary.stat.exists
    - name: Install Go (Linux)
      ansible.builtin.shell: rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go.tar.gz
      become: true
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"] and not go_binary.stat.exists
    - name: Clean up tarball (Linux)
      ansible.builtin.file:
        path: /tmp/go.tar.gz
        state: absent
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"] and not go_binary.stat.exists
    - name: Add Go to shell config
      ansible.builtin.blockinfile:
        path: ~/.zshrc
        create: true
        marker: "# {mark} GO"
        block: |
          export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
    - name: Install Go dev tools
      ansible.builtin.shell: |
        export PATH=$PATH:/usr/local/go/bin
        go install mvdan.cc/gofumpt@latest
        go install golang.org/x/tools/cmd/goimports@latest
        go install golang.org/x/tools/gopls@latest
