---
- name: Install Go on macOS
  hosts: all
  gather_facts: false

  vars:
    go_version: "1.23.4"

  tasks:
    - name: Check if Go is installed
      stat:
        path: /usr/local/go/bin/go
      register: go_binary

    - name: Download Go installer
      get_url:
        url: "https://go.dev/dl/go{{ go_version }}.darwin-arm64.pkg"
        dest: /tmp/go.pkg
      when: not go_binary.stat.exists

    - name: Install Go
      command: installer -pkg /tmp/go.pkg -target /
      become: yes
      when: not go_binary.stat.exists

    - name: Clean up installer
      file:
        path: /tmp/go.pkg
        state: absent
      when: not go_binary.stat.exists
