---
- name: Install Starship
  hosts: all
  gather_facts: true

  tasks:
    - name: Install Starship via Homebrew
      ansible.builtin.shell: /opt/homebrew/bin/brew install starship
      args:
        creates: /opt/homebrew/bin/starship
      when: ansible_facts['os_family'] == "Darwin"

    - name: Check if Starship is installed (Debian)
      ansible.builtin.stat:
        path: /usr/local/bin/starship
      register: starship_check
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Starship via curl (Debian)
      # SECURITY: Starship installer cannot be pinned - no versioned installer exists
      # Alternative: Download binary directly with checksum from GitHub releases
      # https://github.com/starship/starship/releases (provides SHA256 checksums)
      ansible.builtin.shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
      become: true
      when: ansible_facts['os_family'] == "Debian" and not starship_check.stat.exists

    - name: Install Starship via pacman (Arch)
      community.general.pacman:
        name: starship
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Create zsh config directory
      ansible.builtin.file:
        path: ~/.config/zsh
        state: directory

    - name: Install starship zsh config
      ansible.builtin.copy:
        src: starship.zsh
        dest: ~/.config/zsh/starship.zsh

    - name: Source starship in zshrc
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: 'source ~/.config/zsh/starship.zsh'
        create: true

    - name: Install starship config
      ansible.builtin.copy:
        src: starship.toml
        dest: ~/.config/starship.toml
