---
# Zsh installation - minimal setup with defaults
- name: Install zsh (Debian/Ubuntu)
  apt:
    name: zsh
    state: present
  become: true
  when: ansible_os_family == "Debian"
  tags: zsh

- name: Install zsh (macOS)
  homebrew:
    name: zsh
    state: present
  when: ansible_os_family == "Darwin"
  tags: zsh

- name: Install zsh (Arch Linux)
  pacman:
    name: zsh
    state: present
  become: true
  when: ansible_os_family == "Archlinux"
  tags: zsh

- name: Change default shell to zsh
  user:
    name: "{{ user_name }}"
    shell: /bin/zsh
  become: true
  tags: zsh
