---
- name: Install fd
  hosts: all
  gather_facts: true

  tasks:
    - name: Install fd via Homebrew
      shell: /opt/homebrew/bin/brew install fd
      args:
        creates: /opt/homebrew/bin/fd
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install fd via apt
      apt:
        name: fd-find
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian"
