---
- import_playbook: ../node/install_node.yml

- name: Install OpenAI Codex CLI
  hosts: with_ai_tools:&with_login_tools
  gather_facts: true

  tasks:
    - name: Install Codex via npm (macOS)
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        . /opt/homebrew/opt/nvm/nvm.sh
        npm install -g @openai/codex
      args:
        creates: ~/.nvm/versions/node/*/bin/codex
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install Codex via npm (Linux)
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        . ~/.nvm/nvm.sh
        npm install -g @openai/codex
      args:
        creates: ~/.nvm/versions/node/*/bin/codex
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"]
