- name: Install procs
  hosts: all
  gather_facts: true
  tasks:
    - name: Install procs via Homebrew
      ansible.builtin.shell: /opt/homebrew/bin/brew install procs
      args:
        creates: /opt/homebrew/bin/procs
      when: ansible_facts['os_family'] == "Darwin"
    - name: Check if procs is installed (Debian)
      ansible.builtin.stat:
        path: /usr/local/bin/procs
      register: procs_check
      when: ansible_facts['os_family'] == "Debian"
    - name: Download and install procs (Debian)
      ansible.builtin.shell: |
        curl -Lo /tmp/procs.zip "https://github.com/dalance/procs/releases/latest/download/procs-v0.14.8-x86_64-linux.zip"
        unzip -o /tmp/procs.zip -d /tmp
        install /tmp/procs /usr/local/bin
        rm -f /tmp/procs /tmp/procs.zip
      become: true
      when: ansible_facts['os_family'] == "Debian" and not procs_check.stat.exists
    - name: Install procs via pacman (Arch)
      community.general.pacman:
        name: procs
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
