- name: Install lazygit
  hosts: all
  gather_facts: true
  vars:
    lazygit_version: "0.44.1"
  tasks:
    - name: Install lazygit via Homebrew
      ansible.builtin.shell: /opt/homebrew/bin/brew install lazygit
      args:
        creates: /opt/homebrew/bin/lazygit
      when: ansible_facts['os_family'] == "Darwin"
    - name: Check if lazygit is installed (Debian)
      ansible.builtin.stat:
        path: /usr/local/bin/lazygit
      register: lazygit_check
      when: ansible_facts['os_family'] == "Debian"
    - name: Download and install lazygit (Debian)
      ansible.builtin.shell: |
        curl -Lo /tmp/lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz"
        tar xf /tmp/lazygit.tar.gz -C /tmp lazygit
        install /tmp/lazygit /usr/local/bin
        rm -f /tmp/lazygit /tmp/lazygit.tar.gz
      become: true
      when: ansible_facts['os_family'] == "Debian" and not lazygit_check.stat.exists
    - name: Install lazygit via pacman (Arch)
      community.general.pacman:
        name: lazygit
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
    - name: Create zsh config directory
      ansible.builtin.file:
        path: ~/.config/zsh
        state: directory
    - name: Install lazygit aliases
      ansible.builtin.copy:
        src: lazygit.zsh
        dest: ~/.config/zsh/lazygit.zsh
    - name: Source lazygit aliases in zshrc
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: 'source ~/.config/zsh/lazygit.zsh'
        create: true
    - name: Create lazygit config directory
      ansible.builtin.file:
        path: ~/.config/lazygit
        state: directory
    - name: Install lazygit config
      ansible.builtin.copy:
        src: config.yml
        dest: ~/.config/lazygit/config.yml
