---
# Zsh configuration defaults
zsh_theme: "agnoster"
zsh_plugins:
  - git
  - docker
  - kubectl
  - terraform
  - ansible
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - zsh-completions

zsh_zinit_plugins:
  - "zdharma-continuum/fast-syntax-highlighting"
  - "zsh-users/zsh-autosuggestions"
  - "zsh-users/zsh-completions"
