---
- name: Configure Debian system preferences
  hosts: debian
  gather_facts: false

  tasks:
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}.home.lan"
      become: yes
