---
- name: Install build-essential
  hosts: all
  gather_facts: true

  tasks:
    - name: Install build-essential via apt (Debian)
      ansible.builtin.apt:
        name: build-essential
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install base-devel via pacman (Arch)
      community.general.pacman:
        name: base-devel
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
