---
- name: Install Steam
  hosts: with_games
  gather_facts: true

  tasks:
    - name: Install Steam via Homebrew (macOS)
      ansible.builtin.shell: /opt/homebrew/bin/brew install --cask steam
      args:
        creates: /Applications/Steam.app
      when: ansible_facts['os_family'] == "Darwin"

    - name: Add i386 architecture (Debian)
      ansible.builtin.command: dpkg --add-architecture i386
      become: true
      changed_when: false
      when: ansible_facts['os_family'] == "Debian"

    - name: Update apt cache (Debian)
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Steam via apt (Debian)
      ansible.builtin.apt:
        name: steam
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Enable multilib repository (Arch)
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        regexp: '^#?\[multilib\]'
        line: '[multilib]'
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Enable multilib Include (Arch)
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        insertafter: '^\[multilib\]'
        line: 'Include = /etc/pacman.d/mirrorlist'
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Install Steam via pacman (Arch)
      community.general.pacman:
        name: steam
        state: present
        update_cache: true
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
