---
- name: Install and configure zsh
  hosts: all
  gather_facts: true

  tasks:
    - name: Verify zsh is installed (macOS)
      raw: which zsh
      changed_when: false
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install zsh via apt
      apt:
        name: zsh
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Set zsh as default shell (Debian)
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
      become: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install zshrc
      copy:
        src: zshrc
        dest: ~/.zshrc
