---
- name: Install fastfetch
  hosts: all
  gather_facts: true

  tasks:
    - name: Install fastfetch (macOS)
      community.general.homebrew:
        name: fastfetch
        state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install fastfetch (Debian/Ubuntu)
      ansible.builtin.apt:
        name: fastfetch
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install fastfetch (Arch)
      community.general.pacman:
        name: fastfetch
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
