# Apply TokyoNight Storm color scheme to all themed tools
#
# Usage:
#   ansible-playbook themes/colors_tokyonight.yml
- name: Apply TokyoNight colors
  hosts: all
  gather_facts: true
  tasks:
    # tmux - status-style
    - name: Update tmux status-style
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: 'status-style "bg=#[0-9a-fA-F]{6},fg=#[0-9a-fA-F]{6}"'
        replace: 'status-style "bg=#24283b,fg=#c0caf5"'
    # tmux - status-left
    - name: Update tmux status-left
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: 'status-left "#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6},bold\](.+?)#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6}\](.+?)#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6}\](.+?)#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6}\]'
        replace: 'status-left "#[fg=#1a1b26,bg=#7aa2f7,bold]\1#[fg=#7aa2f7,bg=#3b4261]\2#[fg=#c0caf5,bg=#3b4261]\3#[fg=#3b4261,bg=#24283b]'
    # tmux - status-right
    - name: Update tmux status-right
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: 'status-right "#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6}\](.+?)#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6}\](.+?)#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6}\](.+?)#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6},bold\]'
        replace: 'status-right "#[fg=#3b4261,bg=#24283b]\1#[fg=#9aa5ce,bg=#3b4261]\2#[fg=#7aa2f7,bg=#3b4261]\3#[fg=#1a1b26,bg=#7aa2f7,bold]'
    # tmux - window-status-format
    - name: Update tmux window-status-format
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: 'window-status-format "#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6}\]'
        replace: 'window-status-format "#[fg=#565f89,bg=#24283b]'
    # tmux - window-status-current-format
    - name: Update tmux window-status-current-format
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: 'window-status-current-format "#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6}\](.+?)#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6},bold\](.+?)#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6}\]([^"]+)"'
        replace: 'window-status-current-format "#[fg=#24283b,bg=#7aa2f7]\1#[fg=#1a1b26,bg=#7aa2f7,bold]\2#[fg=#7aa2f7,bg=#24283b]\3"'
    # tmux - pane borders
    - name: Update tmux pane-border-style
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: 'pane-border-style "fg=#[0-9a-fA-F]{6}"'
        replace: 'pane-border-style "fg=#3b4261"'
    - name: Update tmux pane-active-border-style
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: 'pane-active-border-style "fg=#[0-9a-fA-F]{6}"'
        replace: 'pane-active-border-style "fg=#7aa2f7"'
    # tmux - messages
    - name: Update tmux message-style
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: 'message-style "bg=#[0-9a-fA-F]{6},fg=#[0-9a-fA-F]{6}"'
        replace: 'message-style "bg=#3b4261,fg=#7aa2f7"'
    - name: Update tmux message-command-style
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: 'message-command-style "bg=#[0-9a-fA-F]{6},fg=#[0-9a-fA-F]{6}"'
        replace: 'message-command-style "bg=#3b4261,fg=#7aa2f7"'
    - name: Update tmux mode-style
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: 'mode-style "bg=#[0-9a-fA-F]{6},fg=#[0-9a-fA-F]{6}"'
        replace: 'mode-style "bg=#3b4261,fg=#7aa2f7"'
    # tmux - theme comment
    - name: Update tmux theme comment
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '^# .+ colors$'
        replace: '# TokyoNight Storm colors'
    # wezterm
    - name: Update wezterm color scheme
      ansible.builtin.replace:
        path: ~/.wezterm.lua
        regexp: 'color_scheme = "[^"]+"'
        replace: 'color_scheme = "tokyonight"'
    # starship - use capture groups to ONLY change hex colors, preserving special chars
    - name: Update starship style_user colors
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(style_user = "fg:#)[0-9a-fA-F]{6}( bg:#)[0-9a-fA-F]{6}( bold")'
        replace: '\g<1>1a1b26\g<2>7aa2f7\g<3>'
    - name: Update starship style_root colors
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(style_root = "fg:#)[0-9a-fA-F]{6}( bg:#)[0-9a-fA-F]{6}( bold")'
        replace: '\g<1>1a1b26\g<2>f7768e\g<3>'
    - name: Update starship username format colors
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(\$user.+\]\(fg:#)[0-9a-fA-F]{6}( bg:#)[0-9a-fA-F]{6}(\)")'
        replace: '\g<1>7aa2f7\g<2>3b4261\g<3>'
    - name: Update starship hostname style colors
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(\[hostname\]\nssh_only = false\nstyle = "fg:#)[0-9a-fA-F]{6}( bg:#)[0-9a-fA-F]{6}(")'
        replace: '\g<1>c0caf5\g<2>3b4261\g<3>'
    - name: Update starship hostname format colors
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(\$hostname.+\]\(fg:#)[0-9a-fA-F]{6}( bg:#)[0-9a-fA-F]{6}(\)")'
        replace: '\g<1>3b4261\g<2>565f89\g<3>'
    - name: Update starship directory style colors
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(\[directory\]\nstyle = "fg:#)[0-9a-fA-F]{6}( bg:#)[0-9a-fA-F]{6}( bold")'
        replace: '\g<1>c0caf5\g<2>565f89\g<3>'
    - name: Update starship git_branch style colors
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(\[git_branch\]\nstyle = "fg:#)[0-9a-fA-F]{6}( bg:#)[0-9a-fA-F]{6}( bold")'
        replace: '\g<1>c0caf5\g<2>3b4261\g<3>'
    - name: Update starship git_branch format colors
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(format = "\[[^\]]*\]\(fg:#)[0-9a-fA-F]{6}( bg:#)[0-9a-fA-F]{6}(\)\[.+\$branch)'
        replace: '\g<1>565f89\g<2>3b4261\g<3>'
    - name: Update starship git_status style colors
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(\[git_status\]\nstyle = "fg:#)[0-9a-fA-F]{6}( bg:#)[0-9a-fA-F]{6}(")'
        replace: '\g<1>c0caf5\g<2>3b4261\g<3>'
    - name: Update starship git_status format color
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(\$all_status.+\]\(fg:#)[0-9a-fA-F]{6}(\)")'
        replace: '\g<1>3b4261\g<2>'
    - name: Update starship custom dir_end color
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(\[custom\.dir_end\][\s\S]*?format = "\[[^\]]*\]\(fg:#)[0-9a-fA-F]{6}(\)")'
        replace: '\g<1>565f89\g<2>'
    - name: Update starship jobs style color
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(\[jobs\]\nstyle = "fg:#)[0-9a-fA-F]{6}(")'
        replace: '\g<1>7aa2f7\g<2>'
    - name: Update starship cmd_duration style color
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(\[cmd_duration\]\nmin_time = 0\nstyle = "fg:#)[0-9a-fA-F]{6}(")'
        replace: '\g<1>565f89\g<2>'
    - name: Update starship time style color
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(\[time\]\ndisabled = false\nstyle = "fg:#)[0-9a-fA-F]{6}(")'
        replace: '\g<1>565f89\g<2>'
    - name: Update starship character success color
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(success_symbol = ".+bold #)[0-9a-fA-F]{6}(\)")'
        replace: '\g<1>9ece6a\g<2>'
    - name: Update starship character error color
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '(error_symbol = ".+bold #)[0-9a-fA-F]{6}(\)")'
        replace: '\g<1>f7768e\g<2>'
    - name: Update starship theme comment
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '^# Starship configuration - .+$'
        replace: '# Starship configuration - TokyoNight Storm theme'
    # neovim - update colorscheme
    - name: Update neovim colorscheme
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "vim\\.cmd\\.colorscheme '[^']+'"
        replace: "vim.cmd.colorscheme 'tokyonight-night'"
    # neovim - statusline highlights
    - name: Update neovim StMode highlight
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "vim.api.nvim_set_hl\\(0, 'StMode', \\{ fg = '#[0-9a-fA-F]{6}', bg = '#[0-9a-fA-F]{6}', bold = true \\}\\)"
        replace: "vim.api.nvim_set_hl(0, 'StMode', { fg = '#1a1b26', bg = '#7aa2f7', bold = true })"
    - name: Update neovim StModeSep highlight
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "vim.api.nvim_set_hl\\(0, 'StModeSep', \\{ fg = '#[0-9a-fA-F]{6}', bg = '#[0-9a-fA-F]{6}' \\}\\)"
        replace: "vim.api.nvim_set_hl(0, 'StModeSep', { fg = '#7aa2f7', bg = '#24283b' })"
    - name: Update neovim StFile highlight
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "vim.api.nvim_set_hl\\(0, 'StFile', \\{ fg = '#[0-9a-fA-F]{6}', bg = '#[0-9a-fA-F]{6}' \\}\\)"
        replace: "vim.api.nvim_set_hl(0, 'StFile', { fg = '#565f89', bg = '#24283b' })"
    - name: Update neovim StGitSep highlight
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "vim.api.nvim_set_hl\\(0, 'StGitSep', \\{ fg = '#[0-9a-fA-F]{6}', bg = '#[0-9a-fA-F]{6}' \\}\\)"
        replace: "vim.api.nvim_set_hl(0, 'StGitSep', { fg = '#24283b', bg = '#3b4261' })"
    - name: Update neovim StGit highlight
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "vim.api.nvim_set_hl\\(0, 'StGit', \\{ fg = '#[0-9a-fA-F]{6}', bg = '#[0-9a-fA-F]{6}' \\}\\)"
        replace: "vim.api.nvim_set_hl(0, 'StGit', { fg = '#9aa5ce', bg = '#3b4261' })"
    # lazygit
    - name: Update lazygit activeBorderColor
      ansible.builtin.replace:
        path: ~/.config/lazygit/config.yml
        regexp: 'activeBorderColor:\n\s+- "#[0-9a-fA-F]{6}"'
        replace: 'activeBorderColor:\n      - "#7aa2f7"'
    - name: Update lazygit inactiveBorderColor
      ansible.builtin.replace:
        path: ~/.config/lazygit/config.yml
        regexp: 'inactiveBorderColor:\n\s+- "#[0-9a-fA-F]{6}"'
        replace: 'inactiveBorderColor:\n      - "#565f89"'
    - name: Update lazygit optionsTextColor
      ansible.builtin.replace:
        path: ~/.config/lazygit/config.yml
        regexp: 'optionsTextColor:\n\s+- "#[0-9a-fA-F]{6}"'
        replace: 'optionsTextColor:\n      - "#7dcfff"'
    - name: Update lazygit selectedLineBgColor
      ansible.builtin.replace:
        path: ~/.config/lazygit/config.yml
        regexp: 'selectedLineBgColor:\n\s+- "#[0-9a-fA-F]{6}"'
        replace: 'selectedLineBgColor:\n      - "#3b4261"'
    - name: Update lazygit cherryPickedCommitBgColor
      ansible.builtin.replace:
        path: ~/.config/lazygit/config.yml
        regexp: 'cherryPickedCommitBgColor:\n\s+- "#[0-9a-fA-F]{6}"'
        replace: 'cherryPickedCommitBgColor:\n      - "#3b4261"'
    - name: Update lazygit cherryPickedCommitFgColor
      ansible.builtin.replace:
        path: ~/.config/lazygit/config.yml
        regexp: 'cherryPickedCommitFgColor:\n\s+- "#[0-9a-fA-F]{6}"'
        replace: 'cherryPickedCommitFgColor:\n      - "#bb9af7"'
    - name: Update lazygit unstagedChangesColor
      ansible.builtin.replace:
        path: ~/.config/lazygit/config.yml
        regexp: 'unstagedChangesColor:\n\s+- "#[0-9a-fA-F]{6}"'
        replace: 'unstagedChangesColor:\n      - "#f7768e"'
    - name: Update lazygit defaultFgColor
      ansible.builtin.replace:
        path: ~/.config/lazygit/config.yml
        regexp: 'defaultFgColor:\n\s+- "#[0-9a-fA-F]{6}"'
        replace: 'defaultFgColor:\n      - "#c0caf5"'
    - name: Update lazygit searchingActiveBorderColor
      ansible.builtin.replace:
        path: ~/.config/lazygit/config.yml
        regexp: 'searchingActiveBorderColor:\n\s+- "#[0-9a-fA-F]{6}"'
        replace: 'searchingActiveBorderColor:\n      - "#9ece6a"'
    - name: Update lazygit theme comment
      ansible.builtin.replace:
        path: ~/.config/lazygit/config.yml
        regexp: '^# lazygit configuration - .+ theme$'
        replace: '# lazygit configuration - TokyoNight Storm theme'
    # bat
    - name: Update bat theme
      ansible.builtin.replace:
        path: ~/.config/zsh/bat.zsh
        regexp: 'BAT_THEME="[^"]+"'
        replace: 'BAT_THEME="tokyonight_storm"'
    - name: Update bat theme comment
      ansible.builtin.replace:
        path: ~/.config/zsh/bat.zsh
        regexp: '^# Bat configuration - .+ theme$'
        replace: '# Bat configuration - TokyoNight Storm theme'
    # fzf
    - name: Update fzf fg color
      ansible.builtin.replace:
        path: ~/.config/zsh/fzf.zsh
        regexp: 'fg:#[0-9a-fA-F]{6}'
        replace: 'fg:#c0caf5'
    - name: Update fzf bg color
      ansible.builtin.replace:
        path: ~/.config/zsh/fzf.zsh
        regexp: 'bg:#[0-9a-fA-F]{6}'
        replace: 'bg:#24283b'
    - name: Update fzf hl color
      ansible.builtin.replace:
        path: ~/.config/zsh/fzf.zsh
        regexp: 'hl:#[0-9a-fA-F]{6}'
        replace: 'hl:#7aa2f7'
    - name: Update fzf fg+ color
      ansible.builtin.replace:
        path: ~/.config/zsh/fzf.zsh
        regexp: 'fg\+:#[0-9a-fA-F]{6}'
        replace: 'fg+:#c0caf5'
    - name: Update fzf bg+ color
      ansible.builtin.replace:
        path: ~/.config/zsh/fzf.zsh
        regexp: 'bg\+:#[0-9a-fA-F]{6}'
        replace: 'bg+:#3b4261'
    - name: Update fzf hl+ color
      ansible.builtin.replace:
        path: ~/.config/zsh/fzf.zsh
        regexp: 'hl\+:#[0-9a-fA-F]{6}'
        replace: 'hl+:#7dcfff'
    - name: Update fzf info color
      ansible.builtin.replace:
        path: ~/.config/zsh/fzf.zsh
        regexp: 'info:#[0-9a-fA-F]{6}'
        replace: 'info:#9ece6a'
    - name: Update fzf prompt color
      ansible.builtin.replace:
        path: ~/.config/zsh/fzf.zsh
        regexp: 'prompt:#[0-9a-fA-F]{6}'
        replace: 'prompt:#7aa2f7'
    - name: Update fzf pointer color
      ansible.builtin.replace:
        path: ~/.config/zsh/fzf.zsh
        regexp: 'pointer:#[0-9a-fA-F]{6}'
        replace: 'pointer:#bb9af7'
    - name: Update fzf marker color
      ansible.builtin.replace:
        path: ~/.config/zsh/fzf.zsh
        regexp: 'marker:#[0-9a-fA-F]{6}'
        replace: 'marker:#9ece6a'
    - name: Update fzf spinner color
      ansible.builtin.replace:
        path: ~/.config/zsh/fzf.zsh
        regexp: 'spinner:#[0-9a-fA-F]{6}'
        replace: 'spinner:#bb9af7'
    - name: Update fzf header color
      ansible.builtin.replace:
        path: ~/.config/zsh/fzf.zsh
        regexp: 'header:#[0-9a-fA-F]{6}'
        replace: 'header:#7aa2f7'
    - name: Update fzf theme comment
      ansible.builtin.replace:
        path: ~/.config/zsh/fzf.zsh
        regexp: '^# FZF configuration - .+ theme$'
        replace: '# FZF configuration - TokyoNight Storm theme'
    # lazydocker
    - name: Update lazydocker activeBorderColor
      ansible.builtin.replace:
        path: ~/.config/lazydocker/config.yml
        regexp: 'activeBorderColor:\n\s+- "#[0-9a-fA-F]{6}"'
        replace: 'activeBorderColor:\n      - "#7aa2f7"'
    - name: Update lazydocker inactiveBorderColor
      ansible.builtin.replace:
        path: ~/.config/lazydocker/config.yml
        regexp: 'inactiveBorderColor:\n\s+- "#[0-9a-fA-F]{6}"'
        replace: 'inactiveBorderColor:\n      - "#565f89"'
    - name: Update lazydocker optionsTextColor
      ansible.builtin.replace:
        path: ~/.config/lazydocker/config.yml
        regexp: 'optionsTextColor:\n\s+- "#[0-9a-fA-F]{6}"'
        replace: 'optionsTextColor:\n      - "#7dcfff"'
    - name: Update lazydocker selectedLineBgColor
      ansible.builtin.replace:
        path: ~/.config/lazydocker/config.yml
        regexp: 'selectedLineBgColor:\n\s+- "#[0-9a-fA-F]{6}"'
        replace: 'selectedLineBgColor:\n      - "#3b4261"'
    - name: Done
      ansible.builtin.debug:
        msg: |
          TokyoNight Storm colors applied to all tools!
          - tmux: run 'tmux source ~/.tmux.conf'
          - wezterm: restart wezterm
          - starship: changes apply on next prompt
          - neovim: restart neovim
          - lazygit: changes apply on next launch
          - bat: changes apply on next use
          - fzf: restart shell or source ~/.config/zsh/fzf.zsh
          - lazydocker: changes apply on next launch
