# Apply Fantasque Sans Mono Nerd Font
#
# Fantasque Sans Mono is a handwriting-inspired programming font with
# a friendly, casual look. It features distinctive letterforms while
# maintaining excellent readability for code.
#
# Usage:
#   ansible-playbook themes/font_fantasquesansmono.yml
- name: Apply Fantasque Sans Mono Nerd Font
  hosts: all
  gather_facts: true
  tasks:
    # Install font
    - name: Install font via Homebrew (macOS)
      shell: brew install --cask font-fantasque-sans-mono-nerd-font
      args:
        creates: ~/Library/Fonts/FantasqueSansMNerdFont-Regular.ttf
      when: ansible_facts['os_family'] == "Darwin"
    - name: Install font via yay (Arch)
      shell: yay -S --noconfirm ttf-fantasque-sans-mono-nerd
      args:
        creates: /usr/share/fonts/TTF/FantasqueSansMNerdFont-Regular.ttf
      when: ansible_facts['os_family'] == "Archlinux"
    - name: Create fonts directory (Debian)
      file:
        path: ~/.local/share/fonts
        state: directory
      when: ansible_facts['os_family'] == "Debian"
    - name: Check if font exists (Debian)
      stat:
        path: ~/.local/share/fonts/FantasqueSansMNerdFont-Regular.ttf
      register: font_check
      when: ansible_facts['os_family'] == "Debian"
    - name: Download and install font (Debian)
      shell: |
        curl -fLo /tmp/FantasqueSansMono.tar.xz "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FantasqueSansMono.tar.xz"
        tar -xf /tmp/FantasqueSansMono.tar.xz -C ~/.local/share/fonts
        fc-cache -fv
        rm /tmp/FantasqueSansMono.tar.xz
      when: ansible_facts['os_family'] == "Debian" and not font_check.stat.exists
    # Update wezterm config
    - name: Update wezterm font
      ansible.builtin.replace:
        path: ~/.wezterm.lua
        regexp: 'config\.font = wezterm\.font\("[^"]+"\)'
        replace: 'config.font = wezterm.font("FantasqueSansM Nerd Font")'
    - name: Done
      ansible.builtin.debug:
        msg: "Fantasque Sans Mono Nerd Font applied! Restart wezterm to see changes."
