# Apply FiraCode Nerd Font
# Install: brew install --cask font-fira-code-nerd-font
#
# Usage:
#   ansible-playbook themes/font_firacode.yml
- name: Apply FiraCode Nerd Font
  hosts: all
  gather_facts: true
  tasks:
    - name: Update wezterm font
      ansible.builtin.replace:
        path: ~/.wezterm.lua
        regexp: 'config\.font = wezterm\.font\("[^"]+"\)'
        replace: 'config.font = wezterm.font("FiraCode Nerd Font")'
    - name: Done
      ansible.builtin.debug:
        msg: |
          FiraCode Nerd Font applied!
          - Restart wezterm to see changes
          - Install font if missing: brew install --cask font-fira-code-nerd-font
