# Apply slant/diagonal powerline separators to all themed tools
#
# This playbook can RESTORE powerline characters from any state:
#   - From angled (U+E0B0/U+E0B2)
#   - From round (U+E0B4/U+E0B6)
#   - From none/clean (spaces in tmux/starship context)
#   - Already slant (no change)
#
# Target glyphs:
#   U+E0BC (right slant)
#   U+E0BE (left slant)
#
# See README.md "Nerd Font / Powerline Characters" for full documentation.
#
# Usage:
#   ansible-playbook themes/style_slant.yml
- name: Apply slant powerline separators
  hosts: all
  gather_facts: true
  vars:
    # Source glyphs (to be replaced)
    arrow_right: "\uE0B0"
    arrow_left: "\uE0B2"
    round_right: "\uE0B4"
    round_left: "\uE0B6"
    # Target separators
    slant_right: "\uE0BC"
    slant_left: "\uE0BE"
  tasks:
    # ===================
    # TMUX - Global replacement
    # ===================
    - name: Replace angle right with slant in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ arrow_right }}"
        replace: "{{ slant_right }}"

    - name: Replace angle left with slant in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ arrow_left }}"
        replace: "{{ slant_left }}"

    - name: Replace round right with slant in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ round_right }}"
        replace: "{{ slant_right }}"

    - name: Replace round left with slant in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ round_left }}"
        replace: "{{ slant_left }}"

    # TMUX - From none (space at separator positions)
    # status-left and window-status use right arrows
    # status-right uses left arrows
    - name: Restore right separator from none in tmux (status-left)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-left.*)\] #\[fg='
        replace: '\1]{{ slant_right }}#[fg='

    - name: Restore right separator from none in tmux (window-status)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(window-status.*)\] #\[fg='
        replace: '\1]{{ slant_right }}#[fg='

    - name: Restore left separator from none in tmux (status-right)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-right.*)\] #\[fg='
        replace: '\1]{{ slant_left }}#[fg='

    # ===================
    # STARSHIP - Global replacement
    # ===================
    - name: Replace angle right with slant in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ arrow_right }}"
        replace: "{{ slant_right }}"

    - name: Replace angle left with slant in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ arrow_left }}"
        replace: "{{ slant_left }}"

    - name: Replace round right with slant in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ round_right }}"
        replace: "{{ slant_right }}"

    - name: Replace round left with slant in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ round_left }}"
        replace: "{{ slant_left }}"

    # STARSHIP - From none (space in separator brackets)
    - name: Restore separator from none in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '\[ \]\(fg:'
        replace: "[{{ slant_right }}](fg:"

    # ===================
    # NEOVIM - Code replacement
    # ===================
    - name: Update neovim right arrow from angle
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b0\\)"
        replace: "nr2char(0xe0bc)"

    - name: Update neovim left arrow from angle
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b2\\)"
        replace: "nr2char(0xe0be)"

    - name: Update neovim right arrow from round
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b4\\)"
        replace: "nr2char(0xe0bc)"

    - name: Update neovim left arrow from round
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b6\\)"
        replace: "nr2char(0xe0be)"

    - name: Update neovim right arrow from none (space)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(local arrow_right = )' '"
        replace: "\\1vim.fn.nr2char(0xe0bc)"

    - name: Update neovim left arrow from none (space)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(local arrow_left = )' '"
        replace: "\\1vim.fn.nr2char(0xe0be)"

    - name: Done
      ansible.builtin.debug:
        msg: |
          Slant powerline separators applied!
          Target: U+E0BC (right) / U+E0BE (left)
          - tmux: run 'tmux source ~/.tmux.conf'
          - starship: changes apply on next prompt
          - neovim: restart neovim
