# Apply slant/diagonal powerline separators to all themed tools
#
# This playbook can RESTORE powerline characters from any state:
#   - From angled (U+E0B0/U+E0B2)
#   - From round (U+E0B4/U+E0B6)
#   - From none/clean (spaces)
#   - Already slant (no change)
#
# Target glyphs:
#   U+E0BC (right slant)
#   U+E0BE (left slant)
#
# See README.md "Nerd Font / Powerline Characters" for full documentation.
#
# Usage:
#   ansible-playbook themes/style_slant.yml
- name: Apply slant powerline separators
  hosts: all
  gather_facts: true
  vars:
    # Target separators
    slant_right: "\uE0BC"
    slant_left: "\uE0BE"
  tasks:
    # ===================
    # TMUX
    # ===================
    - name: Update tmux right separators in status-left
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(\],bold\])([ \uE0B0\uE0B4\uE0BC])( #h)'
        replace: '\g<1>{{ slant_right }}\g<3>'

    - name: Update tmux right separators after session block
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(bg=#[0-9a-fA-F]{6}\])([ \uE0B0\uE0B4\uE0BC])(#\[fg=)'
        replace: '\g<1>{{ slant_right }}\g<3>'

    - name: Update tmux left separators in status-right
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(bg=#[0-9a-fA-F]{6}\])([ \uE0B2\uE0B6\uE0BE])(#\[fg=)'
        replace: '\g<1>{{ slant_left }}\g<3>'

    - name: Update tmux window-status-current right sep start
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(window-status-current-format "#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6}\])([ \uE0B0\uE0B4\uE0BC])(#\[)'
        replace: '\g<1>{{ slant_right }}\g<3>'

    - name: Update tmux window-status-current right sep end
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(bg=#[0-9a-fA-F]{6}\])([ \uE0B0\uE0B4\uE0BC])(")'
        replace: '\g<1>{{ slant_right }}\g<3>'

    # ===================
    # STARSHIP
    # ===================
    - name: Update starship right separators
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '\[([ \uE0B0\uE0B4\uE0BC])\]\(fg:#'
        replace: '[{{ slant_right }}](fg:#'

    - name: Update starship left separators
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '\[([ \uE0B2\uE0B6\uE0BE])\]\(fg:#'
        replace: '[{{ slant_left }}](fg:#'

    - name: Update starship trailing right separators
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '\[([ \uE0B0\uE0B4\uE0BC])\]\(fg:#([0-9a-fA-F]{6})\)"$'
        replace: '[{{ slant_right }}](fg:#\g<2>)"'

    # ===================
    # NEOVIM
    # ===================
    - name: Update neovim right arrow from angled
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b0\\)"
        replace: "nr2char(0xe0bc)"

    - name: Update neovim left arrow from angled
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b2\\)"
        replace: "nr2char(0xe0be)"

    - name: Update neovim right arrow from round
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b4\\)"
        replace: "nr2char(0xe0bc)"

    - name: Update neovim left arrow from round
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b6\\)"
        replace: "nr2char(0xe0be)"

    - name: Update neovim right arrow from none (space)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(local arrow_right = )' '"
        replace: "\\1vim.fn.nr2char(0xe0bc)"

    - name: Update neovim left arrow from none (space)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(local arrow_left = )' '"
        replace: "\\1vim.fn.nr2char(0xe0be)"

    - name: Done
      ansible.builtin.debug:
        msg: |
          Slant powerline separators applied!
          Target: U+E0BC (right) / U+E0BE (left)
          - tmux: run 'tmux source ~/.tmux.conf'
          - starship: changes apply on next prompt
          - neovim: restart neovim
