# Apply flames powerline separators to all themed tools
#
# Target glyphs:
#   U+E0C0 (right flames)
#   U+E0C2 (left flames)
#
# Usage:
#   ansible-playbook themes/style_flames.yml
- name: Apply flames powerline separators
  hosts: all
  gather_facts: true
  vars:
    # Source glyphs (to be replaced)
    arrow_right: "\uE0B0"
    arrow_left: "\uE0B2"
    round_right: "\uE0B4"
    round_left: "\uE0B6"
    slant_right: "\uE0BC"
    slant_left: "\uE0BE"
    pixels_right: "\uE0C4"
    pixels_left: "\uE0C6"
    ice_right: "\uE0C8"
    ice_left: "\uE0CA"
    # Target separators
    flames_right: "\uE0C0"
    flames_left: "\uE0C2"
  tasks:
    # ===================
    # TMUX - Global replacement
    # ===================
    - name: Replace angle right with flames in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ arrow_right }}"
        replace: "{{ flames_right }}"

    - name: Replace angle left with flames in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ arrow_left }}"
        replace: "{{ flames_left }}"

    - name: Replace round right with flames in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ round_right }}"
        replace: "{{ flames_right }}"

    - name: Replace round left with flames in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ round_left }}"
        replace: "{{ flames_left }}"

    - name: Replace slant right with flames in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ slant_right }}"
        replace: "{{ flames_right }}"

    - name: Replace slant left with flames in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ slant_left }}"
        replace: "{{ flames_left }}"

    - name: Replace pixels right with flames in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ pixels_right }}"
        replace: "{{ flames_right }}"

    - name: Replace pixels left with flames in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ pixels_left }}"
        replace: "{{ flames_left }}"

    - name: Replace ice right with flames in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ ice_right }}"
        replace: "{{ flames_right }}"

    - name: Replace ice left with flames in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ ice_left }}"
        replace: "{{ flames_left }}"

    # TMUX - From none (space at separator positions)
    - name: Restore right separator from none in tmux (status-left, pass 1)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-left.*?)\] #\[fg='
        replace: '\1]{{ flames_right }}#[fg='

    - name: Restore right separator from none in tmux (status-left, pass 2)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-left.*?)\] #\[fg='
        replace: '\1]{{ flames_right }}#[fg='

    - name: Restore right separator from none in tmux (window-status, pass 1)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(window-status.*?)\] #\[fg='
        replace: '\1]{{ flames_right }}#[fg='

    - name: Restore right separator from none in tmux (window-status, pass 2)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(window-status.*?)\] #\[fg='
        replace: '\1]{{ flames_right }}#[fg='

    - name: Restore left separator from none in tmux (status-right, pass 1)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-right.*?)\] #\[fg='
        replace: '\1]{{ flames_left }}#[fg='

    - name: Restore left separator from none in tmux (status-right, pass 2)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-right.*?)\] #\[fg='
        replace: '\1]{{ flames_left }}#[fg='

    - name: Restore trailing right separator in tmux (status-left)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-left.*?)\]  "'
        replace: '\1]{{ flames_right }} "'

    - name: Restore trailing right separator in tmux (window-status, two spaces)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(window-status-current.*?)\]  "'
        replace: '\1]{{ flames_right }} "'

    - name: Restore trailing right separator in tmux (window-status, one space)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(window-status-current.*?)\] "'
        replace: '\1]{{ flames_right }}"'

    - name: Restore trailing left separator in tmux (status-right)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-right.*?)\]  "'
        replace: '\1]{{ flames_left }} "'

    # ===================
    # STARSHIP - Global replacement
    # ===================
    - name: Replace angle right with flames in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ arrow_right }}"
        replace: "{{ flames_right }}"

    - name: Replace angle left with flames in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ arrow_left }}"
        replace: "{{ flames_left }}"

    - name: Replace round right with flames in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ round_right }}"
        replace: "{{ flames_right }}"

    - name: Replace round left with flames in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ round_left }}"
        replace: "{{ flames_left }}"

    - name: Replace slant right with flames in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ slant_right }}"
        replace: "{{ flames_right }}"

    - name: Replace slant left with flames in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ slant_left }}"
        replace: "{{ flames_left }}"

    - name: Replace pixels right with flames in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ pixels_right }}"
        replace: "{{ flames_right }}"

    - name: Replace pixels left with flames in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ pixels_left }}"
        replace: "{{ flames_left }}"

    - name: Replace ice right with flames in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ ice_right }}"
        replace: "{{ flames_right }}"

    - name: Replace ice left with flames in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ ice_left }}"
        replace: "{{ flames_left }}"

    - name: Restore separator from none in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '\[ \]\(fg:'
        replace: "[{{ flames_right }}](fg:"

    # ===================
    # NEOVIM - Code replacement
    # ===================
    - name: Update neovim right arrow from angle
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b0\\)"
        replace: "nr2char(0xe0c0)"

    - name: Update neovim left arrow from angle
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b2\\)"
        replace: "nr2char(0xe0c2)"

    - name: Update neovim right arrow from round
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b4\\)"
        replace: "nr2char(0xe0c0)"

    - name: Update neovim left arrow from round
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b6\\)"
        replace: "nr2char(0xe0c2)"

    - name: Update neovim right arrow from slant
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0bc\\)"
        replace: "nr2char(0xe0c0)"

    - name: Update neovim left arrow from slant
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0be\\)"
        replace: "nr2char(0xe0c2)"

    - name: Update neovim right arrow from pixels
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0c4\\)"
        replace: "nr2char(0xe0c0)"

    - name: Update neovim left arrow from pixels
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0c6\\)"
        replace: "nr2char(0xe0c2)"

    - name: Update neovim right arrow from ice
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0c8\\)"
        replace: "nr2char(0xe0c0)"

    - name: Update neovim left arrow from ice
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0ca\\)"
        replace: "nr2char(0xe0c2)"

    - name: Update neovim right arrow from none (space)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(local arrow_right = )' '"
        replace: "\\1vim.fn.nr2char(0xe0c0)"

    - name: Update neovim left arrow from none (space)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(local arrow_left = )' '"
        replace: "\\1vim.fn.nr2char(0xe0c2)"

    - name: Done
      ansible.builtin.debug:
        msg: |
          Flames powerline separators applied!
          Target: U+E0C0 (right) / U+E0C2 (left)
          - tmux: run 'tmux source ~/.tmux.conf'
          - starship: changes apply on next prompt
          - neovim: restart neovim
