# Apply round/semicircle powerline separators to all themed tools
#
# This playbook can RESTORE powerline characters from any state:
#   - From angled (U+E0B0/U+E0B2)
#   - From slant (U+E0BC/U+E0BE)
#   - From none/clean (spaces in tmux/starship context)
#   - Already round (no change)
#
# Target glyphs:
#   U+E0B4 (right round)
#   U+E0B6 (left round)
#
# See README.md "Nerd Font / Powerline Characters" for full documentation.
#
# Usage:
#   ansible-playbook themes/style_round.yml
- name: Apply round powerline separators
  hosts: all
  gather_facts: true
  vars:
    # Source glyphs (to be replaced)
    arrow_right: "\uE0B0"
    arrow_left: "\uE0B2"
    slant_right: "\uE0BC"
    slant_left: "\uE0BE"
    # Target separators
    round_right: "\uE0B4"
    round_left: "\uE0B6"
  tasks:
    # ===================
    # TMUX - Global replacement
    # ===================
    - name: Replace angle right with round in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ arrow_right }}"
        replace: "{{ round_right }}"

    - name: Replace angle left with round in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ arrow_left }}"
        replace: "{{ round_left }}"

    - name: Replace slant right with round in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ slant_right }}"
        replace: "{{ round_right }}"

    - name: Replace slant left with round in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ slant_left }}"
        replace: "{{ round_left }}"

    # ===================
    # STARSHIP - Global replacement
    # ===================
    - name: Replace angle right with round in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ arrow_right }}"
        replace: "{{ round_right }}"

    - name: Replace angle left with round in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ arrow_left }}"
        replace: "{{ round_left }}"

    - name: Replace slant right with round in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ slant_right }}"
        replace: "{{ round_right }}"

    - name: Replace slant left with round in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ slant_left }}"
        replace: "{{ round_left }}"

    # ===================
    # NEOVIM - Code replacement
    # ===================
    - name: Update neovim right arrow from angle
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b0\\)"
        replace: "nr2char(0xe0b4)"

    - name: Update neovim left arrow from angle
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b2\\)"
        replace: "nr2char(0xe0b6)"

    - name: Update neovim right arrow from slant
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0bc\\)"
        replace: "nr2char(0xe0b4)"

    - name: Update neovim left arrow from slant
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0be\\)"
        replace: "nr2char(0xe0b6)"

    - name: Update neovim right arrow from none (space)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(local arrow_right = )' '"
        replace: "\\1vim.fn.nr2char(0xe0b4)"

    - name: Update neovim left arrow from none (space)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(local arrow_left = )' '"
        replace: "\\1vim.fn.nr2char(0xe0b6)"

    - name: Done
      ansible.builtin.debug:
        msg: |
          Round powerline separators applied!
          Target: U+E0B4 (right) / U+E0B6 (left)
          - tmux: run 'tmux source ~/.tmux.conf'
          - starship: changes apply on next prompt
          - neovim: restart neovim
