# Apply round/semicircle powerline separators to all themed tools
#
# This playbook can RESTORE powerline characters from any state:
#   - From angled (U+E0B0/U+E0B2)
#   - From slant (U+E0BC/U+E0BE)
#   - From none/clean (spaces)
#   - Already round (no change)
#
# Target glyphs:
#   U+E0B4 (right round)
#   U+E0B6 (left round)
#
# See README.md "Nerd Font / Powerline Characters" for full documentation.
#
# Usage:
#   ansible-playbook themes/style_round.yml
- name: Apply round powerline separators
  hosts: all
  gather_facts: true
  vars:
    # Target separators
    round_right: "\uE0B4"
    round_left: "\uE0B6"
  tasks:
    # ===================
    # TMUX
    # ===================
    - name: Update tmux right separators in status-left
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(\],bold\])([ \uE0B0\uE0B4\uE0BC])( #h)'
        replace: '\g<1>{{ round_right }}\g<3>'

    - name: Update tmux right separators after session block
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(bg=#[0-9a-fA-F]{6}\])([ \uE0B0\uE0B4\uE0BC])(#\[fg=)'
        replace: '\g<1>{{ round_right }}\g<3>'

    - name: Update tmux left separators in status-right
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(bg=#[0-9a-fA-F]{6}\])([ \uE0B2\uE0B6\uE0BE])(#\[fg=)'
        replace: '\g<1>{{ round_left }}\g<3>'

    - name: Update tmux window-status-current right sep start
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(window-status-current-format "#\[fg=#[0-9a-fA-F]{6},bg=#[0-9a-fA-F]{6}\])([ \uE0B0\uE0B4\uE0BC])(#\[)'
        replace: '\g<1>{{ round_right }}\g<3>'

    - name: Update tmux window-status-current right sep end
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(bg=#[0-9a-fA-F]{6}\])([ \uE0B0\uE0B4\uE0BC])(")'
        replace: '\g<1>{{ round_right }}\g<3>'

    # ===================
    # STARSHIP
    # ===================
    - name: Update starship right separators
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '\[([ \uE0B0\uE0B4\uE0BC])\]\(fg:#'
        replace: '[{{ round_right }}](fg:#'

    - name: Update starship left separators
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '\[([ \uE0B2\uE0B6\uE0BE])\]\(fg:#'
        replace: '[{{ round_left }}](fg:#'

    - name: Update starship trailing right separators
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '\[([ \uE0B0\uE0B4\uE0BC])\]\(fg:#([0-9a-fA-F]{6})\)"$'
        replace: '[{{ round_right }}](fg:#\g<2>)"'

    # ===================
    # NEOVIM
    # ===================
    - name: Update neovim right arrow from angled
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b0\\)"
        replace: "nr2char(0xe0b4)"

    - name: Update neovim left arrow from angled
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b2\\)"
        replace: "nr2char(0xe0b6)"

    - name: Update neovim right arrow from slant
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0bc\\)"
        replace: "nr2char(0xe0b4)"

    - name: Update neovim left arrow from slant
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0be\\)"
        replace: "nr2char(0xe0b6)"

    - name: Update neovim right arrow from none (space)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(local arrow_right = )' '"
        replace: "\\1vim.fn.nr2char(0xe0b4)"

    - name: Update neovim left arrow from none (space)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(local arrow_left = )' '"
        replace: "\\1vim.fn.nr2char(0xe0b6)"

    - name: Done
      ansible.builtin.debug:
        msg: |
          Round powerline separators applied!
          Target: U+E0B4 (right) / U+E0B6 (left)
          - tmux: run 'tmux source ~/.tmux.conf'
          - starship: changes apply on next prompt
          - neovim: restart neovim
