# Apply slant/diagonal powerline separators to all themed tools
#
# Changes angled or round glyphs to slanted glyphs:
#   U+E0B0 (right arrow) -> U+E0BC (slant right)
#   U+E0B2 (left arrow)  -> U+E0BE (slant left)
#   U+E0B4 (right round) -> U+E0BC (slant right)
#   U+E0B6 (left round)  -> U+E0BE (slant left)
#
# This playbook demonstrates the recommended pattern for editing Nerd Font
# characters: use \uXXXX escape sequences in Ansible variables rather than
# raw Unicode characters, which display inconsistently in editors and LLMs.
#
# See README.md "Nerd Font / Powerline Characters" for full documentation.
#
# Usage:
#   ansible-playbook themes/style_slant.yml
- name: Apply slant powerline separators
  hosts: all
  gather_facts: true
  vars:
    # Angled separators (possible current)
    arrow_right: "\uE0B0"
    arrow_left: "\uE0B2"
    # Round separators (possible current)
    round_right: "\uE0B4"
    round_left: "\uE0B6"
    # Slant separators (target)
    slant_right: "\uE0BC"
    slant_left: "\uE0BE"
  tasks:
    # ===================
    # TMUX
    # ===================
    - name: Update tmux angled right arrows to slant
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ arrow_right }}"
        replace: "{{ slant_right }}"

    - name: Update tmux angled left arrows to slant
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ arrow_left }}"
        replace: "{{ slant_left }}"

    - name: Update tmux round right arrows to slant
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ round_right }}"
        replace: "{{ slant_right }}"

    - name: Update tmux round left arrows to slant
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ round_left }}"
        replace: "{{ slant_left }}"

    # ===================
    # STARSHIP
    # ===================
    - name: Update starship angled right arrows to slant
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ arrow_right }}"
        replace: "{{ slant_right }}"

    - name: Update starship angled left arrows to slant
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ arrow_left }}"
        replace: "{{ slant_left }}"

    - name: Update starship round right arrows to slant
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ round_right }}"
        replace: "{{ slant_right }}"

    - name: Update starship round left arrows to slant
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ round_left }}"
        replace: "{{ slant_left }}"

    # ===================
    # NEOVIM
    # ===================
    # Neovim uses vim.fn.nr2char(0xe0b0) format, so we replace the hex codes
    - name: Update neovim angled right arrow to slant (0xe0b0 -> 0xe0bc)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: 'nr2char\(0xe0b0\)'
        replace: 'nr2char(0xe0bc)'

    - name: Update neovim angled left arrow to slant (0xe0b2 -> 0xe0be)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: 'nr2char\(0xe0b2\)'
        replace: 'nr2char(0xe0be)'

    - name: Update neovim round right arrow to slant (0xe0b4 -> 0xe0bc)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: 'nr2char\(0xe0b4\)'
        replace: 'nr2char(0xe0bc)'

    - name: Update neovim round left arrow to slant (0xe0b6 -> 0xe0be)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: 'nr2char\(0xe0b6\)'
        replace: 'nr2char(0xe0be)'

    # Also handle any comments referencing the old characters
    - name: Update neovim arrow comment (right angled)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(--.*arrow.*){{ arrow_right }}"
        replace: "\\1{{ slant_right }}"

    - name: Update neovim arrow comment (left angled)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(--.*arrow.*){{ arrow_left }}"
        replace: "\\1{{ slant_left }}"

    - name: Update neovim arrow comment (right round)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(--.*arrow.*){{ round_right }}"
        replace: "\\1{{ slant_right }}"

    - name: Update neovim arrow comment (left round)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(--.*arrow.*){{ round_left }}"
        replace: "\\1{{ slant_left }}"

    - name: Done
      ansible.builtin.debug:
        msg: |
          Slant powerline separators applied to all tools!
          Changed: angled/round -> U+E0BC/U+E0BE (slant)
          - tmux: run 'tmux source ~/.tmux.conf'
          - starship: changes apply on next prompt
          - neovim: restart neovim
