# Apply angled/chevron powerline separators to all themed tools
#
# This playbook can RESTORE powerline characters from any state:
#   - From round (U+E0B4/U+E0B6)
#   - From slant (U+E0BC/U+E0BE)
#   - From none/clean (spaces in tmux/starship context)
#   - Already angled (no change)
#
# Target glyphs:
#   U+E0B0 (right angle)
#   U+E0B2 (left angle)
#
# See README.md "Nerd Font / Powerline Characters" for full documentation.
#
# Usage:
#   ansible-playbook themes/style_angle.yml
- name: Apply angled powerline separators
  hosts: all
  gather_facts: true
  vars:
    # Source glyphs (to be replaced)
    round_right: "\uE0B4"
    round_left: "\uE0B6"
    slant_right: "\uE0BC"
    slant_left: "\uE0BE"
    pixels_right: "\uE0C4"
    pixels_left: "\uE0C6"
    flames_right: "\uE0C0"
    flames_left: "\uE0C2"
    ice_right: "\uE0C8"
    ice_left: "\uE0CA"
    # Target separators
    arrow_right: "\uE0B0"
    arrow_left: "\uE0B2"
  tasks:
    # ===================
    # TMUX - Global replacement
    # ===================
    - name: Replace round right with angle in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ round_right }}"
        replace: "{{ arrow_right }}"

    - name: Replace round left with angle in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ round_left }}"
        replace: "{{ arrow_left }}"

    - name: Replace slant right with angle in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ slant_right }}"
        replace: "{{ arrow_right }}"

    - name: Replace slant left with angle in tmux
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: "{{ slant_left }}"
        replace: "{{ arrow_left }}"

    # TMUX - From none (space at separator positions)
    # Run twice to catch multiple occurrences per line (regex backrefs match one at a time)
    - name: Restore right separator from none in tmux (status-left, pass 1)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-left.*?)\] #\[fg='
        replace: '\1]{{ arrow_right }}#[fg='

    - name: Restore right separator from none in tmux (status-left, pass 2)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-left.*?)\] #\[fg='
        replace: '\1]{{ arrow_right }}#[fg='

    - name: Restore right separator from none in tmux (window-status, pass 1)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(window-status.*?)\] #\[fg='
        replace: '\1]{{ arrow_right }}#[fg='

    - name: Restore right separator from none in tmux (window-status, pass 2)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(window-status.*?)\] #\[fg='
        replace: '\1]{{ arrow_right }}#[fg='

    - name: Restore left separator from none in tmux (status-right, pass 1)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-right.*?)\] #\[fg='
        replace: '\1]{{ arrow_left }}#[fg='

    - name: Restore left separator from none in tmux (status-right, pass 2)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-right.*?)\] #\[fg='
        replace: '\1]{{ arrow_left }}#[fg='

    # Trailing separators (at end of format strings before closing ")
    - name: Restore trailing right separator in tmux (status-left)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-left.*?)\]  "'
        replace: '\1]{{ arrow_right }} "'

    - name: Restore trailing right separator in tmux (window-status, two spaces)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(window-status-current.*?)\]  "'
        replace: '\1]{{ arrow_right }} "'

    - name: Restore trailing right separator in tmux (window-status, one space)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(window-status-current.*?)\] "'
        replace: '\1]{{ arrow_right }}"'

    - name: Restore trailing left separator in tmux (status-right)
      ansible.builtin.replace:
        path: ~/.tmux.conf
        regexp: '(status-right.*?)\]  "'
        replace: '\1]{{ arrow_left }} "'

    # ===================
    # STARSHIP - Global replacement
    # ===================
    - name: Replace round right with angle in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ round_right }}"
        replace: "{{ arrow_right }}"

    - name: Replace round left with angle in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ round_left }}"
        replace: "{{ arrow_left }}"

    - name: Replace slant right with angle in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ slant_right }}"
        replace: "{{ arrow_right }}"

    - name: Replace slant left with angle in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: "{{ slant_left }}"
        replace: "{{ arrow_left }}"

    # STARSHIP - From none (space in separator brackets)
    # Pattern: [ ](fg: means single space between [ and ](fg:
    - name: Restore separator from none in starship
      ansible.builtin.replace:
        path: ~/.config/starship.toml
        regexp: '\[ \]\(fg:'
        replace: "[{{ arrow_right }}](fg:"

    # ===================
    # NEOVIM - Code replacement
    # ===================
    - name: Update neovim right arrow from round
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b4\\)"
        replace: "nr2char(0xe0b0)"

    - name: Update neovim left arrow from round
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0b6\\)"
        replace: "nr2char(0xe0b2)"

    - name: Update neovim right arrow from slant
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0bc\\)"
        replace: "nr2char(0xe0b0)"

    - name: Update neovim left arrow from slant
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "nr2char\\(0xe0be\\)"
        replace: "nr2char(0xe0b2)"

    - name: Update neovim right arrow from none (space)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(local arrow_right = )' '"
        replace: "\\1vim.fn.nr2char(0xe0b0)"

    - name: Update neovim left arrow from none (space)
      ansible.builtin.replace:
        path: ~/.config/nvim/init.lua
        regexp: "(local arrow_left = )' '"
        replace: "\\1vim.fn.nr2char(0xe0b2)"

    - name: Done
      ansible.builtin.debug:
        msg: |
          Angled powerline separators applied!
          Target: U+E0B0 (right) / U+E0B2 (left)
          - tmux: run 'tmux source ~/.tmux.conf'
          - starship: changes apply on next prompt
          - neovim: restart neovim
