---
- name: Configure keyboard (remap Caps Lock to Ctrl)
  hosts: all
  gather_facts: true

  tasks:
    # ============================================
    # macOS - hidutil (kernel level, persisted via LaunchAgent)
    # ============================================
    - name: Create LaunchAgents directory (macOS)
      ansible.builtin.file:
        path: ~/Library/LaunchAgents
        state: directory
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install Caps Lock to Ctrl remap LaunchAgent (macOS)
      ansible.builtin.copy:
        src: com.local.KeyRemapping.plist
        dest: ~/Library/LaunchAgents/com.local.KeyRemapping.plist
      when: ansible_facts['os_family'] == "Darwin"

    - name: Load keyboard remap LaunchAgent (macOS)
      ansible.builtin.command: launchctl load ~/Library/LaunchAgents/com.local.KeyRemapping.plist
      changed_when: false
      failed_when: false
      when: ansible_facts['os_family'] == "Darwin"

    - name: Apply keyboard remap immediately (macOS)
      ansible.builtin.command: >-
        hidutil property --set
        '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,
        "HIDKeyboardModifierMappingDst":0x7000000E0}]}'
      changed_when: false
      when: ansible_facts['os_family'] == "Darwin"

    # ============================================
    # Linux - keyd (kernel/evdev level - works everywhere)
    # ============================================
    - name: Install keyd (Arch)
      community.general.pacman:
        name: keyd
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Check if keyd is available in apt (Debian)
      ansible.builtin.shell: apt-cache show keyd 2>/dev/null
      register: keyd_apt_check
      changed_when: false
      failed_when: false
      when: ansible_facts['os_family'] == "Debian"

    - name: Install keyd from apt if available (Debian)
      ansible.builtin.apt:
        name: keyd
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian" and keyd_apt_check.rc == 0

    - name: Install keyd build dependencies (Debian - if not in apt)
      ansible.builtin.apt:
        name:
          - build-essential
          - git
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian" and keyd_apt_check.rc != 0

    - name: Clone keyd repository (Debian - if not in apt)
      ansible.builtin.git:
        repo: https://github.com/rvaiya/keyd.git
        dest: /tmp/keyd
        version: master
      when: ansible_facts['os_family'] == "Debian" and keyd_apt_check.rc != 0

    - name: Build and install keyd (Debian - if not in apt)
      ansible.builtin.shell: |
        cd /tmp/keyd
        make
        make install
      args:
        creates: /usr/local/bin/keyd
      become: true
      when: ansible_facts['os_family'] == "Debian" and keyd_apt_check.rc != 0

    - name: Create keyd config directory
      ansible.builtin.file:
        path: /etc/keyd
        state: directory
        mode: '0755'
      become: true
      when: ansible_facts['os_family'] in ["Archlinux", "Debian"]

    - name: Configure keyd to remap Caps Lock to Ctrl
      ansible.builtin.copy:
        dest: /etc/keyd/default.conf
        content: |
          [ids]
          *

          [main]
          capslock = leftcontrol
        mode: '0644'
      become: true
      register: keyd_config
      when: ansible_facts['os_family'] in ["Archlinux", "Debian"]

    - name: Enable keyd service
      ansible.builtin.systemd:
        name: keyd
        enabled: true
        state: started
      become: true
      when: ansible_facts['os_family'] in ["Archlinux", "Debian"]

    - name: Reload keyd if config changed
      ansible.builtin.command: keyd reload
      become: true
      when: ansible_facts['os_family'] in ["Archlinux", "Debian"] and keyd_config.changed
