---
- name: Install htop
  hosts: all
  gather_facts: true

  tasks:
    - name: Install htop via Homebrew (macOS)
      shell: /opt/homebrew/bin/brew install htop
      args:
        creates: /opt/homebrew/bin/htop
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install htop via apt (Debian)
      apt:
        name: htop
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install htop via pacman (Arch)
      pacman:
        name: htop
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Archlinux"
