---
- name: Install htop
  hosts: all
  gather_facts: true

  tasks:
    - name: Install htop via Homebrew (macOS)
      ansible.builtin.shell: /opt/homebrew/bin/brew install htop
      args:
        creates: /opt/homebrew/bin/htop
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install htop via apt (Debian)
      ansible.builtin.apt:
        name: htop
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install htop via pacman (Arch)
      community.general.pacman:
        name: htop
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
