- name: Install zsh-autosuggestions
  hosts: all
  gather_facts: true
  tasks:
    - name: Install zsh-autosuggestions via Homebrew
      shell: /opt/homebrew/bin/brew install zsh-autosuggestions
      args:
        creates: /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
      when: ansible_facts['os_family'] == "Darwin"
    - name: Install zsh-autosuggestions via apt (Debian)
      apt:
        name: zsh-autosuggestions
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: Install zsh-autosuggestions via pacman (Arch)
      pacman:
        name: zsh-autosuggestions
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Archlinux"
    - name: Create zsh config directory
      file:
        path: ~/.config/zsh
        state: directory
    - name: Install zsh-autosuggestions loader
      copy:
        src: zsh-autosuggestions.zsh
        dest: ~/.config/zsh/zsh-autosuggestions.zsh
    - name: Source zsh-autosuggestions in zshrc
      lineinfile:
        path: ~/.zshrc
        line: source ~/.config/zsh/zsh-autosuggestions.zsh
        create: yes
