---
- name: Install and configure Git
  hosts: all
  gather_facts: true

  tasks:
    - name: Install git via apt (Debian)
      ansible.builtin.apt:
        name: git
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install git via pacman (Arch)
      community.general.pacman:
        name: git
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Install gitconfig (macOS with login)
      ansible.builtin.template:
        src: gitconfig.darwin.j2
        dest: ~/.gitconfig
      when: ansible_facts['os_family'] == "Darwin" and 'with_login_tools' in group_names

    - name: Install gitconfig (Linux with login)
      ansible.builtin.template:
        src: gitconfig.debian.j2
        dest: ~/.gitconfig
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"] and 'with_login_tools' in group_names

    - name: Install gitconfig (minimal)
      ansible.builtin.template:
        src: gitconfig.minimal.j2
        dest: ~/.gitconfig
      when: "'with_login_tools' not in group_names"

    - name: Create zsh config directory
      ansible.builtin.file:
        path: ~/.config/zsh
        state: directory

    - name: Install git aliases
      ansible.builtin.copy:
        src: git.zsh
        dest: ~/.config/zsh/git.zsh

    - name: Source git aliases in zshrc
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: 'source ~/.config/zsh/git.zsh'
        create: true
