---
- name: Install Neovim
  hosts: all
  gather_facts: true

  tasks:
    - name: Install Neovim via Homebrew
      shell: /opt/homebrew/bin/brew install neovim
      args:
        creates: /opt/homebrew/bin/nvim
      when: ansible_facts['os_family'] == "Darwin"

    - name: Check if Neovim is installed
      stat:
        path: /usr/local/bin/nvim
      register: nvim_check
      when: ansible_facts['os_family'] == "Debian"

    - name: Download and install Neovim from GitHub
      shell: |
        curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim-linux-x86_64.tar.gz
        tar xzf nvim-linux-x86_64.tar.gz
        cp -r nvim-linux-x86_64/* /usr/local/
        rm -rf nvim-linux-x86_64 nvim-linux-x86_64.tar.gz
      args:
        chdir: /tmp
      become: yes
      when: ansible_facts['os_family'] == "Debian" and not nvim_check.stat.exists

    - name: Check if kickstart.nvim is installed
      stat:
        path: ~/.config/nvim/init.lua
      register: kickstart_check

    - name: Install kickstart.nvim
      git:
        repo: https://github.com/nvim-lua/kickstart.nvim.git
        dest: ~/.config/nvim
        depth: 1
      when: not kickstart_check.stat.exists
