- name: Install Neovim
  hosts: all
  gather_facts: true
  tasks:
    - name: Install Neovim via Homebrew
      ansible.builtin.shell: /opt/homebrew/bin/brew install neovim
      args:
        creates: /opt/homebrew/bin/nvim
      when: ansible_facts['os_family'] == "Darwin"
    - name: Check if Neovim is installed (Debian)
      ansible.builtin.stat:
        path: /usr/local/bin/nvim
      register: nvim_check
      when: ansible_facts['os_family'] == "Debian"
    - name: Download and install Neovim from GitHub (Debian)
      ansible.builtin.shell: |
        curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim-linux-x86_64.tar.gz
        tar xzf nvim-linux-x86_64.tar.gz
        cp -r nvim-linux-x86_64/* /usr/local/
        rm -rf nvim-linux-x86_64 nvim-linux-x86_64.tar.gz
      args:
        chdir: /tmp
      become: true
      when: ansible_facts['os_family'] == "Debian" and not nvim_check.stat.exists
    - name: Install Neovim via pacman (Arch)
      community.general.pacman:
        name: neovim
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
    - name: Remove existing neovim config
      ansible.builtin.file:
        path: ~/.config/nvim
        state: absent
    - name: Install neovim config
      ansible.builtin.copy:
        src: nvim/
        dest: ~/.config/nvim/
    - name: Create zsh config directory
      ansible.builtin.file:
        path: ~/.config/zsh
        state: directory
    - name: Install neovim environment
      ansible.builtin.copy:
        src: neovim.zsh
        dest: ~/.config/zsh/neovim.zsh
    - name: Source neovim environment in zshrc
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: 'source ~/.config/zsh/neovim.zsh'
        create: true
    - name: Install Mason language servers
      vars:
        mason_packages: >-
          typescript-language-server eslint-lsp css-lsp html-lsp json-lsp
          tailwindcss-language-server pyright rust-analyzer bash-language-server
          yaml-language-server prettierd stylua shfmt shellcheck black isort ruff
      ansible.builtin.shell: |
        nvim --headless -c "MasonInstall {{ mason_packages | replace('\n', ' ') }}" -c "sleep 30" -c "qa"
      args:
        creates: ~/.local/share/nvim/mason/bin/typescript-language-server
      ignore_errors: true
