---
- name: Install Neovim
  hosts: all
  gather_facts: true

  tasks:
    - name: Install Neovim via Homebrew
      shell: /opt/homebrew/bin/brew install neovim
      args:
        creates: /opt/homebrew/bin/nvim
      when: ansible_os_family == "Darwin"

    - name: Install Neovim via apt
      apt:
        name: neovim
        state: present
      become: yes
      when: ansible_os_family == "Debian"

    - name: Check if kickstart.nvim is installed
      stat:
        path: ~/.config/nvim/init.lua
      register: kickstart_check

    - name: Install kickstart.nvim
      git:
        repo: https://github.com/nvim-lua/kickstart.nvim.git
        dest: ~/.config/nvim
        depth: 1
      when: not kickstart_check.stat.exists
