---
- name: Install Neovim on macOS
  hosts: all
  gather_facts: false

  tasks:
    - name: Install Neovim via Homebrew
      shell: /opt/homebrew/bin/brew install neovim
      args:
        creates: /opt/homebrew/bin/nvim

    - name: Check if kickstart.nvim is installed
      stat:
        path: ~/.config/nvim/init.lua
      register: kickstart_check

    - name: Install kickstart.nvim
      git:
        repo: https://github.com/nvim-lua/kickstart.nvim.git
        dest: ~/.config/nvim
        depth: 1
      when: not kickstart_check.stat.exists
