---
- name: Install yt-dlp
  hosts: all
  gather_facts: true

  tasks:
    - name: Install yt-dlp via Homebrew
      ansible.builtin.shell: /opt/homebrew/bin/brew install yt-dlp
      args:
        creates: /opt/homebrew/bin/yt-dlp
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install yt-dlp via apt (Debian)
      ansible.builtin.apt:
        name: yt-dlp
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install yt-dlp via pacman (Arch)
      community.general.pacman:
        name: yt-dlp
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
