- name: Install zsh-syntax-highlighting
  hosts: all
  gather_facts: true
  tasks:
    - name: Install zsh-syntax-highlighting via Homebrew
      shell: /opt/homebrew/bin/brew install zsh-syntax-highlighting
      args:
        creates: /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
      when: ansible_facts['os_family'] == "Darwin"
    - name: Install zsh-syntax-highlighting via apt (Debian)
      apt:
        name: zsh-syntax-highlighting
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: Install zsh-syntax-highlighting via pacman (Arch)
      pacman:
        name: zsh-syntax-highlighting
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Archlinux"
    - name: Create zsh config directory
      file:
        path: ~/.config/zsh
        state: directory
    - name: Install zsh-syntax-highlighting loader
      copy:
        src: zsh-syntax-highlighting.zsh
        dest: ~/.config/zsh/zsh-syntax-highlighting.zsh
    - name: Source zsh-syntax-highlighting in zshrc
      lineinfile:
        path: ~/.zshrc
        line: source ~/.config/zsh/zsh-syntax-highlighting.zsh
        create: yes
