---
- name: Install Node.js (dependency for MCP servers)
  import_playbook: ../node/install_node.yml

- name: Install Claude Code
  hosts: with_ai_tools:&with_login_tools
  gather_facts: true

  tasks:
    - name: Install Claude Code via native installer
      ansible.builtin.shell: curl -fsSL https://claude.ai/install.sh | bash

    - name: Create Claude config directory
      ansible.builtin.file:
        path: ~/.claude
        state: directory

    - name: Create Claude config scaffold directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.claude/commands
        - ~/.claude/agents
        - ~/.claude/hooks

    - name: Deploy ansible-lint hook for _dotfiles repo
      ansible.builtin.copy:
        src: hooks/ansible-lint.sh
        dest: ~/.claude/hooks/ansible-lint.sh
        mode: "0755"

    - name: Deploy /idea command
      ansible.builtin.copy:
        src: commands/idea.md
        dest: ~/.claude/commands/idea.md

    - name: Add/update Sequential Thinking MCP server (user level)
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        {% if ansible_facts['os_family'] == "Darwin" %}
        . /opt/homebrew/opt/nvm/nvm.sh
        {% else %}
        . ~/.nvm/nvm.sh
        {% endif %}
        claude mcp remove --scope user thinking 2>/dev/null || true
        claude mcp add --scope user --transport stdio thinking -- npx -y @modelcontextprotocol/server-sequential-thinking@latest
      changed_when: true
      failed_when: false

    - name: Add/update Context7 MCP server (user level)
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        {% if ansible_facts['os_family'] == "Darwin" %}
        . /opt/homebrew/opt/nvm/nvm.sh
        {% else %}
        . ~/.nvm/nvm.sh
        {% endif %}
        claude mcp remove --scope user context7 2>/dev/null || true
        claude mcp add --scope user --transport stdio context7 -- npx -y @upstash/context7-mcp@latest
      changed_when: true
      failed_when: false

    - name: Add/update Playwright MCP server (user level)
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        {% if ansible_facts['os_family'] == "Darwin" %}
        . /opt/homebrew/opt/nvm/nvm.sh
        {% else %}
        . ~/.nvm/nvm.sh
        {% endif %}
        claude mcp remove --scope user playwright 2>/dev/null || true
        claude mcp add --scope user --transport stdio playwright -- npx -y @playwright/mcp@latest
      changed_when: true
      failed_when: false

    # https://github.com/glittercowboy/get-shit-done
    - name: Install/update Get Shit Done (GSD) commands (user level)
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        {% if ansible_facts['os_family'] == "Darwin" %}
        . /opt/homebrew/opt/nvm/nvm.sh
        {% else %}
        . ~/.nvm/nvm.sh
        {% endif %}
        npx -y get-shit-done-cc@latest --global
      changed_when: true
