---
- import_playbook: ../node/install_node.yml

- name: Install Claude Code
  hosts: with_ai_tools:&with_login_tools
  gather_facts: true

  tasks:
    - name: Install/update Claude Code via npm (macOS)
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        . /opt/homebrew/opt/nvm/nvm.sh
        npm install -g @anthropic-ai/claude-code@latest
      register: claude_install_mac
      changed_when: "'added' in claude_install_mac.stdout or 'updated' in claude_install_mac.stderr"
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install/update Claude Code via npm (Linux)
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        . ~/.nvm/nvm.sh
        npm install -g @anthropic-ai/claude-code@latest
      register: claude_install_linux
      changed_when: "'added' in claude_install_linux.stdout or 'updated' in claude_install_linux.stderr"
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"]

    - name: Create Claude config directory
      ansible.builtin.file:
        path: ~/.claude
        state: directory

    - name: Create Claude config scaffold directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.claude/commands
        - ~/.claude/agents
        - ~/.claude/hooks

    - name: Add/update Sequential Thinking MCP server (user level)
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        {% if ansible_facts['os_family'] == "Darwin" %}
        . /opt/homebrew/opt/nvm/nvm.sh
        {% else %}
        . ~/.nvm/nvm.sh
        {% endif %}
        claude mcp remove --scope user thinking 2>/dev/null || true
        claude mcp add --scope user --transport stdio thinking -- npx -y @modelcontextprotocol/server-sequential-thinking@latest
      changed_when: true
      failed_when: false

    - name: Add/update Playwright MCP server (user level)
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        {% if ansible_facts['os_family'] == "Darwin" %}
        . /opt/homebrew/opt/nvm/nvm.sh
        {% else %}
        . ~/.nvm/nvm.sh
        {% endif %}
        claude mcp remove --scope user playwright 2>/dev/null || true
        claude mcp add --scope user --transport stdio playwright -- npx -y @playwright/mcp@latest
      changed_when: true
      failed_when: false

    # https://github.com/glittercowboy/get-shit-done
    - name: Install/update Get Shit Done (GSD) commands (user level)
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        {% if ansible_facts['os_family'] == "Darwin" %}
        . /opt/homebrew/opt/nvm/nvm.sh
        {% else %}
        . ~/.nvm/nvm.sh
        {% endif %}
        npx -y get-shit-done-cc@latest --global
      changed_when: true
