---
- import_playbook: ../node/install_node.yml

- name: Install Claude Code
  hosts: with_ai_tools:&with_login_tools
  gather_facts: true

  tasks:
    - name: Install Claude Code via npm (macOS)
      shell: |
        export NVM_DIR="$HOME/.nvm"
        . /opt/homebrew/opt/nvm/nvm.sh
        npm install -g @anthropic-ai/claude-code
      args:
        creates: ~/.nvm/versions/node/*/bin/claude
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install Claude Code via npm (Linux)
      shell: |
        export NVM_DIR="$HOME/.nvm"
        . ~/.nvm/nvm.sh
        npm install -g @anthropic-ai/claude-code
      args:
        creates: ~/.nvm/versions/node/*/bin/claude
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"]

    - name: Create Claude config directory
      file:
        path: ~/.claude
        state: directory

    - name: Create Claude hooks directory
      file:
        path: ~/.claude/hooks
        state: directory

    - name: Install Claude Code settings
      copy:
        src: settings.json
        dest: ~/.claude/settings.json

    - name: Install Claude Code auto-checkpoint hook
      copy:
        src: hooks/auto-checkpoint.sh
        dest: ~/.claude/hooks/auto-checkpoint.sh
        mode: '0755'

    - name: Create Claude agents directory
      file:
        path: ~/.claude/agents
        state: directory

    - name: Install Claude Code custom agents
      copy:
        src: agents/
        dest: ~/.claude/agents/

    - name: Create Claude output-styles directory
      file:
        path: ~/.claude/output-styles
        state: directory

    - name: Install Claude Code output styles
      copy:
        src: output-styles/
        dest: ~/.claude/output-styles/

    - name: Add Sequential Thinking MCP server (user level)
      shell: |
        export NVM_DIR="$HOME/.nvm"
        {% if ansible_facts['os_family'] == "Darwin" %}
        . /opt/homebrew/opt/nvm/nvm.sh
        {% else %}
        . ~/.nvm/nvm.sh
        {% endif %}
        claude mcp add --scope user --transport stdio thinking -- npx -y @modelcontextprotocol/server-sequential-thinking
      register: mcp_result
      changed_when: "'Added' in mcp_result.stdout"
      failed_when: false

    - name: Add Playwright MCP server (user level)
      shell: |
        export NVM_DIR="$HOME/.nvm"
        {% if ansible_facts['os_family'] == "Darwin" %}
        . /opt/homebrew/opt/nvm/nvm.sh
        {% else %}
        . ~/.nvm/nvm.sh
        {% endif %}
        claude mcp add --scope user --transport stdio playwright -- npx -y @anthropic/mcp-server-playwright
      register: mcp_playwright_result
      changed_when: "'Added' in mcp_playwright_result.stdout"
      failed_when: false
