---
- import_playbook: ../node/install_node.yml

- name: Install Claude Code
  hosts: with_ai_tools:&with_login_tools
  gather_facts: true

  tasks:
    - name: Install Claude Code via npm (macOS)
      shell: |
        export NVM_DIR="$HOME/.nvm"
        . /opt/homebrew/opt/nvm/nvm.sh
        npm install -g @anthropic-ai/claude-code
      args:
        creates: ~/.nvm/versions/node/*/bin/claude
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install Claude Code via npm (Linux)
      shell: |
        export NVM_DIR="$HOME/.nvm"
        . ~/.nvm/nvm.sh
        npm install -g @anthropic-ai/claude-code
      args:
        creates: ~/.nvm/versions/node/*/bin/claude
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"]
