---
- import_playbook: ../node/install_node.yml

- name: Install Claude Code
  hosts: with_ai_tools:&with_login_tools
  gather_facts: true

  tasks:
    - name: Install/update Claude Code via npm (macOS)
      shell: |
        export NVM_DIR="$HOME/.nvm"
        . /opt/homebrew/opt/nvm/nvm.sh
        npm install -g @anthropic-ai/claude-code@latest
      register: claude_install_mac
      changed_when: "'added' in claude_install_mac.stdout or 'updated' in claude_install_mac.stderr"
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install/update Claude Code via npm (Linux)
      shell: |
        export NVM_DIR="$HOME/.nvm"
        . ~/.nvm/nvm.sh
        npm install -g @anthropic-ai/claude-code@latest
      register: claude_install_linux
      changed_when: "'added' in claude_install_linux.stdout or 'updated' in claude_install_linux.stderr"
      when: ansible_facts['os_family'] in ["Debian", "Archlinux"]

    - name: Create Claude config directory
      file:
        path: ~/.claude
        state: directory

    - name: Create Claude hooks directory
      file:
        path: ~/.claude/hooks
        state: directory

    - name: Install Claude Code settings
      copy:
        src: settings.json
        dest: ~/.claude/settings.json

    - name: Install Claude Code auto-commit hook
      copy:
        src: hooks/auto-commit.sh
        dest: ~/.claude/hooks/auto-commit.sh
        mode: "0755"

    - name: Create Claude agents directory
      file:
        path: ~/.claude/agents
        state: directory

    - name: Install Claude Code custom agents
      copy:
        src: agents/
        dest: ~/.claude/agents/

    - name: Create Claude output-styles directory
      file:
        path: ~/.claude/output-styles
        state: directory

    - name: Install Claude Code output styles
      copy:
        src: output-styles/
        dest: ~/.claude/output-styles/

    - name: Add/update Sequential Thinking MCP server (user level)
      shell: |
        export NVM_DIR="$HOME/.nvm"
        {% if ansible_facts['os_family'] == "Darwin" %}
        . /opt/homebrew/opt/nvm/nvm.sh
        {% else %}
        . ~/.nvm/nvm.sh
        {% endif %}
        claude mcp remove --scope user thinking 2>/dev/null || true
        claude mcp add --scope user --transport stdio thinking -- npx -y @modelcontextprotocol/server-sequential-thinking@latest
      changed_when: true
      failed_when: false

    - name: Add/update Playwright MCP server (user level)
      shell: |
        export NVM_DIR="$HOME/.nvm"
        {% if ansible_facts['os_family'] == "Darwin" %}
        . /opt/homebrew/opt/nvm/nvm.sh
        {% else %}
        . ~/.nvm/nvm.sh
        {% endif %}
        claude mcp remove --scope user playwright 2>/dev/null || true
        claude mcp add --scope user --transport stdio playwright -- npx -y @playwright/mcp@latest
      changed_when: true
      failed_when: false

    - name: Install/update Get Shit Done (GSD) commands (user level)
      shell: |
        export NVM_DIR="$HOME/.nvm"
        {% if ansible_facts['os_family'] == "Darwin" %}
        . /opt/homebrew/opt/nvm/nvm.sh
        {% else %}
        . ~/.nvm/nvm.sh
        {% endif %}
        npx -y get-shit-done-cc@latest --global
      changed_when: true
