---
- name: Install Microsoft Edge
  hosts: with_browsers
  gather_facts: true

  tasks:
    - name: Install Microsoft Edge via Homebrew Cask (macOS)
      ansible.builtin.shell: /opt/homebrew/bin/brew install --cask microsoft-edge
      args:
        creates: /Applications/Microsoft Edge.app
      when: ansible_facts['os_family'] == "Darwin"

    - name: Check if Edge is installed (Debian)
      ansible.builtin.stat:
        path: /usr/bin/microsoft-edge
      register: edge_check
      when: ansible_facts['os_family'] == "Debian"

    - name: Add Microsoft Edge apt repository (Debian)
      ansible.builtin.shell: |
        curl -fsSL https://packages.microsoft.com/keys/microsoft.asc \
          | gpg --dearmor -o /usr/share/keyrings/microsoft-edge.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-edge.gpg] \
          https://packages.microsoft.com/repos/edge stable main" \
          | tee /etc/apt/sources.list.d/microsoft-edge.list > /dev/null
      become: true
      when:
        - ansible_facts['os_family'] == "Debian"
        - ansible_facts.architecture == "x86_64"
        - not edge_check.stat.exists

    - name: Install Microsoft Edge via apt (Debian)
      ansible.builtin.apt:
        name: microsoft-edge-stable
        state: present
        update_cache: true
      become: true
      when:
        - ansible_facts['os_family'] == "Debian"
        - ansible_facts.architecture == "x86_64"

    - name: Skip Edge on ARM64 (no Linux packages available)
      ansible.builtin.debug:
        msg: "Microsoft Edge is not available for ARM64 Linux. No alternative installation method exists."
      when:
        - ansible_facts['os_family'] == "Debian"
        - ansible_facts.architecture == "aarch64"

    - name: Install Microsoft Edge via yay (Arch)
      ansible.builtin.shell: yay -S --noconfirm microsoft-edge-stable-bin
      args:
        creates: /usr/bin/microsoft-edge-stable
      when: ansible_facts['os_family'] == "Archlinux"
