---
- name: Install tmux
  hosts: all
  gather_facts: true

  tasks:
    - name: Install tmux via Homebrew
      shell: /opt/homebrew/bin/brew install tmux
      args:
        creates: /opt/homebrew/bin/tmux
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install tmux via apt
      apt:
        name: tmux
        state: present
      become: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install tmux config
      template:
        src: tmux.conf.j2
        dest: ~/.tmux.conf
