---
- name: Install tmux
  hosts: all
  gather_facts: true

  tasks:
    - name: Install tmux via Homebrew
      ansible.builtin.shell: /opt/homebrew/bin/brew install tmux
      args:
        creates: /opt/homebrew/bin/tmux
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install tmux via apt (Debian)
      ansible.builtin.apt:
        name: tmux
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install tmux via pacman (Arch)
      community.general.pacman:
        name: tmux
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Install tmux config
      ansible.builtin.template:
        src: tmux.conf.j2
        dest: ~/.tmux.conf
      register: tmux_config

    - name: Reload tmux config
      ansible.builtin.shell: tmux source-file ~/.tmux.conf
      when: tmux_config.changed and lookup('env', 'TMUX') != ''
      ignore_errors: true
