- name: Install direnv
  hosts: all
  gather_facts: true
  tasks:
    - name: Install direnv via Homebrew
      ansible.builtin.shell: /opt/homebrew/bin/brew install direnv
      args:
        creates: /opt/homebrew/bin/direnv
      when: ansible_facts['os_family'] == "Darwin"
    - name: Install direnv via apt (Debian)
      ansible.builtin.apt:
        name: direnv
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"
    - name: Install direnv via pacman (Arch)
      community.general.pacman:
        name: direnv
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"
    - name: Create zsh config directory
      ansible.builtin.file:
        path: ~/.config/zsh
        state: directory
    - name: Install direnv shell hook
      ansible.builtin.copy:
        src: direnv.zsh
        dest: ~/.config/zsh/direnv.zsh
    - name: Source direnv hook in zshrc
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: source ~/.config/zsh/direnv.zsh
        create: true
