---
- name: Install cowsay
  hosts: all
  gather_facts: true

  tasks:
    - name: Install cowsay (macOS)
      community.general.homebrew:
        name: cowsay
        state: present
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install cowsay (Debian/Ubuntu)
      ansible.builtin.apt:
        name: cowsay
        state: present
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Install cowsay (Arch)
      community.general.pacman:
        name: cowsay
        state: present
      become: true
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Install cowsay aliases
      ansible.builtin.copy:
        src: cowsay.zsh
        dest: ~/.config/zsh/cowsay.zsh

    - name: Source cowsay aliases in zshrc
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: source ~/.config/zsh/cowsay.zsh
        create: true
