---
# Base packages installation role
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"
  tags: always

- name: Install base packages (Debian/Ubuntu)
  apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags: packages

- name: Install base packages (macOS)
  homebrew:
    name: "{{ base_packages }}"
    state: present
  when: ansible_os_family == "Darwin"
  tags: packages

- name: Install base packages (Arch Linux)
  pacman:
    name: "{{ base_packages }}"
    state: present
  when: ansible_os_family == "Archlinux"
  tags: packages

- name: Install build essentials (Debian/Ubuntu)
  apt:
    name: "{{ build_packages }}"
    state: present
  when: ansible_os_family == "Debian"
  tags: packages

- name: Install development tools (macOS)
  command: xcode-select --install
  register: xcode_install
  failed_when: xcode_install.rc != 0 and "already installed" not in xcode_install.stderr
  changed_when: xcode_install.rc == 0
  when: ansible_os_family == "Darwin"
  tags: packages

- name: Install base-devel group (Arch Linux)
  pacman:
    name: base-devel
    state: present
  when: ansible_os_family == "Archlinux"
  tags: packages
